### ISSUE TITLE
$font-family-primary-* is currently not overridable

### ISSUE THREAD

**Issue by jabez007** [inkline/inkline#103]
* **I'm submitting a:**

  - [x] Bug Report
  - [ ] Feature Request

  
* **What is the current behavior?**

following the instructions from the [customization documentation](https://inkline.io/docs/introduction/customization) to set custom fonts [per the typography documentation](https://inkline.io/docs/core/typography) does not override the `-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;` 

the `$font-family-primary-base`, `$font-family-primary-monospace` and `$font-family-primary-print` variables in `_typrography.scss` appear to be missing the `!default` that would allow them to be overriden.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.)

setting the `$font-family-primary-base` variable in our custom SASS should override the `$font-family-primary-base` in `_typography.scss`

**Comment by alexgrozav** [comment]
Fixed in v1.17.5. Thank you for reporting the issue.
