### ISSUE TITLE
Add v-click-outside handler to INavbar

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#107]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**
Currently, the navbar can only be closed from the toggle button and by clicking an item.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)
We should have a `collapseOnClickOutside` prop to hide a Navbar on outside click. There is `v-click-outside` in `src/directives` which can be used for this.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

**Comment by joshuadempsey** [comment]
Is there any progress on this issue @alexgrozav

**Comment by alexgrozav** [comment]
I'll start working on it once the DataTables branch is merged.

**Comment by alexgrozav** [comment]
Added in #129. Please update `@inkline/inkline` to 1.20.4 and read the [release notes](https://github.com/inkline/inkline/releases/tag/v1.20.4).
