### ISSUE TITLE
Class Consistency

### ISSUE THREAD

**Issue by mybigman** [inkline/inkline#109]
* **I'm submitting a:**

  - [X ] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**

Prefixing for classes. Examples.

-responsive
-fluid
-thumbnail

_border-top
_background-primary
_display-inline

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

To be consistent across all classes?

**Comment by alexgrozav** [comment]
Hey, are you referring to the mixed use of dashes `-` and `underlines`?

**Comment by mybigman** [comment]
@alexgrozav  yes

**Comment by alexgrozav** [comment]
Inkline uses RSCSS (https://rscss.io/) for naming classes. It's a components-first naming system that makes it easy to differentiate when you're targeting the styles for a component (i.e. `.button`), a specific component variant (i.e. `.-disabled`), or simply adding a utility class that isn't part of the component itself (i.e. `._margin-top-1`).

The ones with a dash `-` are modifier classes and are used to provide component variants.
The ones with an underline `_` are utility classes and are used to provide convenience styles in various scenarios (different spacing, padding, colors, etc.).
