### ISSUE TITLE
"export 'default' (imported as 'Inkline') was not found in '@inkline/inkline/src/index'

### ISSUE THREAD

**Issue by mybigman** [inkline/inkline#110]
* **I'm submitting a:**

  - [ x] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
Complies with warning -

warning  in ./src/main.js

"export 'default' (imported as 'Inkline') was not found in '@inkline/inkline/src/index'

Same or similar issue as https://github.com/inkline/inkline/issues/97 however I'm not using NUXT

![image](https://user-images.githubusercontent.com/1289916/70107317-3ea50c00-169a-11ea-8b12-974231b203df.png)

![image](https://user-images.githubusercontent.com/1289916/70107951-1e764c80-169c-11ea-9612-fb41bbfd0467.png)

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

Compile without warning.

* **Please tell us about your environment:**

  - Version: 1.18.0
  - Browser: [all]
  - Language: [ES6/7 | ES5]

**Comment by alexgrozav** [comment]
The default export has now moved to `@inkline/inkline/src/main` to provide better tree shaking. 

In `@inkline/inkline/src/index` you will only find the individually exported components.

Is this referenced in the documentation somewhere?

**Comment by mybigman** [comment]
@alexgrozav  thanks for that... the docs would need updating.

https://inkline.io/docs/introduction/installation

Under tree shaking.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1289916/70233828-70f65c80-17b3-11ea-95e1-16c5ed9c1356.png">

It still produces the code warning like my screen shot but atleast its working now as previously it wouldn't render the scss.
