### ISSUE TITLE
Update Popper.js to version 2

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#125]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
Popper.js@2.x has been released and can be found under `@popperjs/core`. Update the `PopupProviderMixin.vue` file.

**Comment by codebender828** [comment]
Hey @alexgrozav ! Would like to take this on if possible! I recently updated Chakra UI Vue's version of Popper.js. Happy to help contribute with this. 🙏🏽

**Comment by alexgrozav** [comment]
@codebender828 That would be amazing. Thank you!  

Let me know if there's anything I can help with. I'm available on Inkline's Discord most of the time :).

**Comment by codebender828** [comment]
Cheers!

**Comment by codebender828** [comment]
How can I join the Discord? @alexgrozav 😄

**Comment by alexgrozav** [comment]
https://discord.com/invite/2w5UGnK

**Comment by alexgrozav** [comment]
Done in #184. @codebender828 @Eternal-Rise Thank you both for the initiative!
