### ISSUE TITLE
Form validate function throwing errors when when executing on a schema.

### ISSUE THREAD

**Issue by Nelepseo** [inkline/inkline#127]
* **I'm submitting a:**

  - [X] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
When executing the function, 
`this.form.validate()`
the error "Cannot read property 'getSchema' of undefined" is thrown. 

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)
For the form to validate without error. 

* **Please tell us about your environment:**

  - Version: 1.20.2
  - Browser: [Chrome | Firefox]
  - Language: [TypeScript X.X | ES6/7 | ES5 ]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)
This issue was fixed when the call was changed to 
`this.form.validate({
      getSchema: () => this.form,
  });`

Tracing back in the function call it was found that the default options for the schema are unset in the call and that is causing the call to error when trying to run functions on the options.

**Comment by alexgrozav** [comment]
I'm looking into it now. Thank you for reporting this.

**Comment by alexgrozav** [comment]
Fixed in #128. Please wait for 1.20.3 release.
