### ISSUE TITLE
Nuxt module appears to be causing nuxt build failure

### ISSUE THREAD

**Issue by jdlennoxs** [inkline/inkline#135]
* **I'm submitting a:**

  - [x] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
Nuxt builds failing when including inkline as a module

`yarn add @inkline/inkline`
Inkline added to nuxt.config as per documentation
Running any nuxt commands results throws a fatal error when looking for the inkline module from the inkline nuxt module. Error below
       
Seemingly an error with the inkline build not being able to find the required packages?
This had been working before a version bump but now throws errors if it is included in nuxt.config

Any ideas on how to debug this further?

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

Expect the build to succeed.

* **Please tell us about your environment:**

  - Version: 1.20.10
  - Browser: [all ]
  - Language: [ES6/7]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

                                                
   │   ✖ Nuxt Fatal Error                                                                    
   │                                                                                         
   │   Error: Cannot find module '../packages/inkline/package.json'                          
   │   Require stack:                                                                       
   │   - /workspace/dev-blog/node_modules/@inkline/inkline/nuxt/index.js   
   │   - /workspace/dev-blog/node_modules/@nuxt/core/dist/core.js          
   │   - /workspace/dev-blog/node_modules/@nuxt/cli/dist/cli-command.js    
   │   - /workspace/dev-blog/node_modules/@nuxt/cli/dist/cli.js            
   │   - /workspace/dev-blog/node_modules/nuxt/bin/nuxt.js

**Comment by alexgrozav** [comment]
I'm looking into it now. Meanwhile, you can add inkline as a plugin by doing the following:

1. Create a plugin file in `plugins/inkline.js`
2. Add the following to it:
~~~js
import Vue from 'vue';
import Inkline from '@inkline/inkline';
import '@inkline/inkline/inkline.scss';

Vue.use(Inkline);
~~~

**Comment by alexgrozav** [comment]
I've added nuxt module integration tests so this shouldn't happen again.

The nuxt module is now available by running `npm install -D @inkline/nuxt`. Make sure you check out the new nuxt.js module documentation here: https://inkline.io/docs/introduction/installation
