### ISSUE TITLE
Sidebar z-index issue

### ISSUE THREAD

**Issue by tomtakumi** [inkline/inkline#137]
* **I'm submitting a:**
  - [X] Bug Report
 
* **What is the current behavior?**
The sidebar position is below the content itself. 

sidebar not collapsed
![image](https://user-images.githubusercontent.com/13040075/75041097-cb9a7d00-54b3-11ea-9751-890583db1286.png)

sidebar collapsed
![image](https://user-images.githubusercontent.com/13040075/75041161-ee2c9600-54b3-11ea-8184-f1ed4d0590d8.png)

* **Please tell us about your environment:**

  - Version: 1.21.0

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

Code
![image](https://user-images.githubusercontent.com/13040075/75041312-3d72c680-54b4-11ea-954c-b2f745f8356c.png)

**Comment by alexgrozav** [comment]
Hey! Thank you for reporting this. The bug should be fixed in #138 . Can you test it out for your case and let me know? 

Please update to 1.21.1 first.

**Comment by tomtakumi** [comment]
Fixed! Thanks for the quick fix.

**Comment by alexgrozav** [comment]
I'm happy to hear that. You're welcome! :)
