### ISSUE TITLE
Ability to add @events(namely @click) to table row in Datatable and disable the search bar in Datatable.

### ISSUE THREAD

**Issue by Nelepseo** [inkline/inkline#149]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**

We are not able to set @click options for rows in the i-datatable component. 
We are also unable to disable and remove the Search Bar inside the i-datatable component as well.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

To be able to set an @click event on  table row and remove/disable the search bar in the component.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [Chrome XX | Firefox XX  
  - Language: [ TypeScript X.X | ES6/7  ]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

We request there to be a way to add @click options to the row elements of the data table. Currently using the custom slot it places the @click option on the wrong element. Currently we have to put the @click on each <td> element to make the <tr> clickable. 

We are also requesting a way to remove/disable the in component search option in some cases we wont/don't need a search available to the end user. A use case for this is say we have our own search component where we query an api and we load in data to the i-datatable component. The user has already searched for an option and we just want to show them results and paginate them.

**Comment by alexgrozav** [comment]
Thank you for the feature request. I'll implement these in the following version (after the dark mode branch is merged).

**Comment by alexgrozav** [comment]
Done in #150 and released under version 1.22.1.

Thank you for the feature request!
