### ISSUE TITLE
Getting a compile error when using this library in nuxt as a universal app.

### ISSUE THREAD

**Issue by Rsalyme** [inkline/inkline#156]
* **I'm submitting a:**
    - [x ] Bug Report
  
* **What is the current behavior?**
I'm getting a compile error when using this library in nuxt as a universal app.

* **What is the expected behavior?** 

    If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

I am just using **nuxt** and **nuxt build** to compile my project.

To reproduce this is the nuxt.config.js:

mode: 'universal',
modules: [
    '@nuxtjs/axios',
    '@nuxtjs/markdownit',
    '@inkline/nuxt',
    ['cookie-universal-nuxt', { alias: 'cookies' }]
  ],
  inkline: {
      treeShaking: true,
      scss: true,
      components: ['ClientOnly','ILayout','ILayoutHeader','ILayoutContent','ILayoutFooter']
  }

Package.json:

"dependencies": {
    "@inkline/nuxt": "^1.22.3",
    "@nuxtjs/axios": "^5.3.1",
    "@nuxtjs/markdownit": "^1.2.1",
    "@salesforce-ux/design-system": "^2.11.6",
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "apollo-link-http": "^1.5.16",
    "apollo-link-ws": "^1.0.19",
    "apollo-utilities": "^1.3.3",
    "auth0-js": "^9.11.3",
    "chart.js": "^2.9.3",
    "cookie-universal-nuxt": "^2.1.3",
    "core-js": "^2.6.11",
    "express": "^4.17.1",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",
    "moment": "^2.22.1",
    "morgan": "^1.9.1",
    "nuxt": "^1.4.0",
    "nuxt-fullpage.js": "^0.0.3",
    "path": "^0.12.7",
    "subscriptions-transport-ws": "^0.9.16",
    "vue": "^2.6.11",
    "vue-apollo": "^3.0.3",
    "vue-chartjs": "^3.5.0",
    "vue-countup-v2": "^4.0.0",
    "vue-server-renderer": "^2.6.11",
    "vuesax": "^3.11.13",
    "vuetable-2": "^1.7.5",
    "vuetning": "^0.4.2"
  },
  "devDependencies": {
    "node-sass": "^4.14.0",
    "sass-loader": "^8.0.2"
  }

* **Please tell us about your environment:**
I'm using this in the chrome but have tried other browsers and gotten the same error.
I'm using nuxt. I'm really only trying to pull the layout components from inkline for now.

 ERROR  Failed to compile with 2 errors                                                                                       4:28:25 PM

 error  in ./node_modules/@inkline/inkline/src/mixins/components/properties/VariantPropertyMixin.vue

Syntax Error: Unexpected token (12:89)

  10 |     },
  11 |     created() {
> 12 |         this.classesProvider.add(() => this.variant ? `-${this.variant}` : this.$inkline?.config?.variant && `-${this.$inkline.co
nfig.variant}`);
     |                                                                                          ^
  13 |     }
  14 | };
  15 | 

 @ ./node_modules/@inkline/inkline/src/mixins/components/properties/VariantPropertyMixin.vue 4:0-308 5:0-321
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/Users/ruud/src/git/ebs-nuxt/node_modules/babel-p
reset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/@inkline/inkline/src/components/Select/script.j
s
 @ ./node_modules/@inkline/inkline/src/components/Select/index.vue
 @ ./node_modules/@inkline/inkline/src/components/index.js
 @ ./.nuxt/inkline.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

 error  in ./node_modules/@inkline/inkline/src/components/Datatable/script.js

Syntax Error: Unexpected token (260:20)

  258 | 
  259 |             // Add row specific classes for current column
> 260 |             if (row?.config?.columns?.[column.path]?.class) {
      |                     ^
  261 |                 classes = classes.concat(row.config.columns[column.path].class);
  262 |             }
  263 | 

 @ ./node_modules/@inkline/inkline/src/components/Datatable/index.vue 8:0-231 9:0-244
 @ ./node_modules/@inkline/inkline/src/components/index.js
 @ ./.nuxt/inkline.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

  nuxt: Call close hooks (2) +4s
  nuxt: server closed +1ms

Any advice or suggestions is greatly appreciated thanks.

**Comment by alexgrozav** [comment]
Hi, it looks like you're missing the following babel plugin: https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining.

This is included in latest versions of nuxt, but since you're using `^1.4.0`, you'relikely don't have it.

**Comment by Rsalyme** [comment]
@alexgrozav Yup that fixed it! I was using an older version of nuxt so I updated to 2.0.0. and that made it work. thanks.

**Comment by alexgrozav** [comment]
Glad I could help. Enjoy!
