### ISSUE TITLE
Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: compound selectors may no longer be extended

### ISSUE THREAD

**Issue by NefixEstrada** [inkline/inkline#157]
* **I'm submitting a:**
    - [x] Bug Report
    - [ ] Feature Request
  
* **What is the current behavior?**
The modules fail to build due a SASS syntax error

* **What is the expected behavior?** 
The modules should build

* **Please tell us about your environment:**
  - Version: 2.0.1
  - Browser: all
  - Language: all

* **Other information** 

See [http://bit.ly/ExtendCompound](http://bit.ly/ExtendCompound)

```
 error  in ./node_modules/@inkline/inkline/src/components/Toggle/style.scss?vue&type=style&index=0&id=706fa902&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: compound selectors may no longer be extended.
Consider `@extend .toggle, .-light` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
45 │     @extend .toggle.-light;
   │             ^^^^^^^^^^^^^^
   ╵
  /frontend/node_modules/@inkline/inkline/src/components/Toggle/style.scss 45:13  root stylesheet

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/@inkline/inkline/src/components/Toggle/style.scss?vue&type=style&index=0&id=706fa902&lang=scss&scoped=true& 4:14-328 14:3-18:5 15:22-336
 @ ./node_modules/@inkline/inkline/src/components/Toggle/style.scss?vue&type=style&index=0&id=706fa902&lang=scss&scoped=true&
 @ ./node_modules/@inkline/inkline/src/components/Toggle/index.vue
 @ ./node_modules/@inkline/inkline/src/components/index.js
 @ ./node_modules/@inkline/inkline/src/index.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.100:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

**Comment by alexgrozav** [comment]
Hey!

This shouldn't happen on a clean installation. Can you give me some more details? 

Which version of `node-sass` are you using? Also, can you list your `package.json` dependencies and devDependencies?

**Comment by alexgrozav** [comment]
Closing because issue creator did not respond for 2 weeks.

**Comment by kindlyfire** [comment]
Fails for me too. Extending compound selectors is deprecated: https://sass-lang.com/documentation/breaking-changes/extend-compound

Installing Inkline on new Vue project fails to compile due to this

**Comment by alexgrozav** [comment]
This will require a rewrite of all of our CSS files. Meanwhile, I'm afraid you'll need to use an earlier SASS version. I'll leave this for v3.
