### ISSUE TITLE
Add full width variant for button group component

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#158]
* **I'm submitting a:**
    - [ ] Bug Report
    - [x] Feature Request
  
* **What is the current behavior?**
IButtonGroup only has width based on child buttons.

* **What is the expected behavior?** 
There should be a `stretch` or `full-width` modifier for the IButtonGroup component to set its child buttons to span full width equally. 

We can use a combination of `display: flex; width: 100%;` on the parent and `flex-basis: 100%` on the child.

* **Other information** 
    Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.

**Comment by renielDev** [comment]
Opened PR for this. Check [Link](https://github.com/inkline/inkline/pull/160)
