### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#159]
* **I'm submitting a:**
    - [ ] Bug Report
    - [x] Feature Request
  
Here you can request what icons you find essential to web applications and should be included in Inkline.

**Comment by alexgrozav** [comment]
For example, a refresh icon would be a great addition.

**Comment by milaan-muc** [comment]
Is there a way to include Fontawesome? In the navbar example it looks like this is the case. How can this be done?

```
<i-nav>
  <i-input class="item" placeholder="Type something..">
    <i-button variant="primary" slot="append">
      <font-awesome-icon icon="search" />
    </i-button>
  </i-input>
</i-nav>
```

**Comment by alexgrozav** [comment]
I'm working on a way to make inkline's icon component universal, and allow users to import font-awesome icons dynamically.

**Comment by alexgrozav** [comment]
This is currently possible using the `@inkline/inkline@next` version, together with the new `@inkline/icons` package.
