### ISSUE TITLE
Add IToast component and notification service

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#162]
* **I'm submitting a:**
    - [ ] Bug Report
    - [x] Feature Request
  
* **What is the current behavior?**
We do not have a notification service. We should be able to generate a toast notification using `this.$inkline.notification(options)`.

* **What is the expected behavior?** 
It would be worth exploring a vue-toasted integration https://www.npmjs.com/package/vue-toasted.

**Comment by masihtak** [comment]
I'd like to work on this feature 😀

**Comment by alexgrozav** [comment]
That would be awesome, @masihtak! 😃

**Comment by alexgrozav** [comment]
Added in Inkline 4.
