### ISSUE TITLE
Add example pages

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#165]
* **I'm submitting a:**
    - [ ] Bug Report
    - [x] Feature Request
  
We need to add some example pages for homepage, dashboard, blog and ecommerce. These will be displayed in the `Introduction` section of the documentation, under `Examples`. Perhaps we should consider implementing them in an interactive coding environment.

**Comment by milaan-muc** [comment]
This would be awesome. I'm currently looking how to create a Single Page App using Inkline.
How, for example, could i make i-layout-content use all height of the page or i-layout-footer to stick to the bottom of the window?

**Comment by alexgrozav** [comment]
Thanks for the feedback.

It's definitely possible to do. All you'd have to do is add some custom CSS to the `i-layout-footer` as follows:

~~~
<i-layout-footer id="footer">
~~~

~~~
#footer {
    position: fixed;
    width: 100%;
    bottom: 0;
    left: 0;
    z-index: 1;
}
~~~
