### ISSUE TITLE
Add an autocomplete component

### ISSUE THREAD

**Issue by garp360** [inkline/inkline#174]
* **I'm submitting a:**
    - [ ] Bug Report
    - [x] Feature Request
  
* **What is the current behavior?**
Missing
* **What is the expected behavior?** 
A component similar to a select box that will fetch matching data as the user enters text.  The user will then be able to select from the list or keep what is entered.  The component should be designed to match the theme of Inkline.

**Comment by alexgrozav** [comment]
Hi! The `i-select` component has been designed in such a way that it will support adding autocomplete at some point. Therefore, you can be sure it's on it's way! :)

**Comment by alexgrozav** [comment]
We now have a beautifully working autocomplete component in **Inkline 3**. Cheers!
