### ISSUE TITLE
Form submit auto click first button

### ISSUE THREAD

**Issue by Eternal-Rise** [inkline/inkline#176]
* **I'm submitting a:**
    - [x] Bug Report
    - [ ] Feature Request
  
* **What is the current behavior?**
If form is invalid and user press "enter", the first ```<button>``` in the form is triggered "click".
 
* **What is the expected behavior?** 
Prevent submitting

**Comment by alexgrozav** [comment]
Fixed in 2.2.2. Looks like it happened when I simplified the `i-form` and `schema` transmission. Thank you for reporting the issue!
