### ISSUE TITLE
ReferenceError: options is not defined

### ISSUE THREAD

**Issue by anonimusprogramus** [inkline/inkline#180]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
   - install vue with vue-cli
   - install Inkline following [docs](https://inkline.io/docs/introduction/installation/vue-cli)
   - `npm install --save-dev style-resources-loader vue-cli-plugin-style-resources-loader`
   - error happened

* **What is the expected behavior?** 
  
* **What is the current behavior?**
```
⚓  Running completion hooks...
ERROR  ReferenceError: options is not defined
ReferenceError: options is not defined
at addIntegration (/home/i/localhost/0mio/33-my-site/node_modules/@inkline/vue-cli-plugin-inkline/generator/index.js:101:5)
at /home/i/localhost/0mio/33-my-site/node_modules/@inkline/vue-cli-plugin-inkline/generator/index.js:124:3
at runGenerator (/home/i/.nvm/versions/node/v12.14.0/lib/node_modules/@vue/cli/lib/invoke.js:132:13)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async invoke (/home/i/.nvm/versions/node/v12.14.0/lib/node_modules/@vue/cli/lib/invoke.js:92:3)
```

* **Please tell us about your environment:**
  - Version: 2.0.0
  - Browser: [ Chrome 83 ]
  - Language: [ ES6/7 ]

* **Other information** 
```run on Arch Linux```

**Comment by alexgrozav** [comment]
Hey! Checking it out now. Thanks for reporting this!

**Comment by alexgrozav** [comment]
Found the issue. Should be up as version 2.2.2 in a few minutes.

**Comment by alexgrozav** [comment]
Done! Please try again, it will work properly now. 

Thank you for letting me know about this critical issue. Looks like automated integration tests only go so far..
