### ISSUE TITLE
Bad color experience

### ISSUE THREAD

**Issue by Eternal-Rise** [inkline/inkline#186]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
    ![danger modal](https://i.ibb.co/rpq2hVN/image.png)
    ![default modal](https://i.ibb.co/ZHvPMVy/image.png)

* **What is the expected behavior?**
  Card background must be like page background
  
* **What is the current behavior?**
   Buttons background color is exactly as cards background color. 

* **Please tell us about your environment:**
- `"@inkline/nuxt": "^2.2.3",`

**Comment by alexgrozav** [comment]
You're referring to the modal component, right? Modal colors and most color variables will change in the new PR #185. I'll make sure to fix this one as well. Thank you! :)

**Comment by alexgrozav** [comment]
Should be fixed in the new version (v2.3.0). Can you please confirm?
