### ISSUE TITLE
Select's options appear below collapsible and accordion

### ISSUE THREAD

**Issue by goknsh** [inkline/inkline#192]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
    1. Create an accordion or collapsible.
    2. Create a select with lots and lots of options.

* **What is the expected behavior?** 
    If collapsible: Select's options appear above the collapsible's title and contents (if two items are open)
    If accordion: Select's options appear above the accordion's title
  
* **What is the current behavior?**

* **Please tell us about your environment:**
  - Version: ~2.3.0
  - Browser: [Chromium]
  - Language: [Vue 2.6.11]

* **Other information** 
    Perhaps a fix with z-index. Or I would really like to limit the height of select's dropdown.

**Comment by Eternal-Rise** [comment]
Didn't check v3, but works well in v4
