### ISSUE TITLE
Server compile errors with new 'universal' 'Static' (JAMStack) project

### ISSUE THREAD

**Issue by ArchaicMage** [inkline/inkline#196]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
    If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

1. Create new nuxt.js project
`$ yarn create nuxt-app <project-name>`
![image](https://user-images.githubusercontent.com/12578432/90185050-179fed80-dd84-11ea-8acd-154d6d3babfa.png)

2. Install @inkline/nuxt
`$ yarn add --dev @inkline/nuxt`

3. Install node-sass and sass-loader
`yarn add --dev node-sass sass-loader`

4. Add @inkline/nuxt to nuxt.config.js
![image](https://user-images.githubusercontent.com/12578432/90185272-6fd6ef80-dd84-11ea-8471-30262834ff9b.png)

5. Run nuxt dev server
`$ yarn run dev`

* **What is the expected behavior?** 
  
I expect the Client and Server to compile successfully.

* **What is the current behavior?**

Server does not compile successfully.

![image](https://user-images.githubusercontent.com/12578432/90185408-b0366d80-dd84-11ea-9b2f-22e90c316cd7.png)

* **Please tell us about your environment:**
  - Version: Windows 10 x64 Pro
  - Browser: [all]
  - Node.js: 14.7.0

package.json
```
{
  "name": "inkline-sample",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "lint": "yarn lint:js",
    "test": "jest"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.12.0",
    "@nuxtjs/pwa": "^3.0.0-beta.20",
    "nuxt": "^2.14.0"
  },
  "devDependencies": {
    "@inkline/nuxt": "^2.3.0",
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@vue/test-utils": "^1.0.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.1.0",
    "eslint": "^7.5.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "jest": "^26.1.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.3",
    "vue-jest": "^3.0.4"
  }
}
```

nuxt.config.js
```
export default {
  /*
  ** Nuxt rendering mode
  ** See https://nuxtjs.org/api/configuration-mode
  */
  mode: 'universal',
  /*
  ** Nuxt target
  ** See https://nuxtjs.org/api/configuration-target
  */
  target: 'static',
  /*
  ** Headers of the page
  ** See https://nuxtjs.org/api/configuration-head
  */
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Global CSS
  */
  css: [
  ],
  /*
  ** Plugins to load before mounting the App
  ** https://nuxtjs.org/guide/plugins
  */
  plugins: [
  ],
  /*
  ** Auto import components
  ** See https://nuxtjs.org/api/configuration-components
  */
  components: true,
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/eslint-module'
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@inkline/nuxt'
  ],
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {},
  /*
  ** Build configuration
  ** See https://nuxtjs.org/api/configuration-build/
  */
  build: {
  }
}
```

* **Other information** 
    Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.

I've only been able to get Inkline to work with Nuxt.js through a custom plugin. This works, but is undesirable.

ex. Background image is not shown. It is instead overwritten by a .header style

```
<template>
  <i-header fullscreen :cover="true" class="intro-header _text-center _text-white">
...

<style scoped>
.intro-header {
  background-image: url("~assets/images/intro-header-background.jpeg");
}
...
```

I've attempted to;
- Add @inkline to Nuxt.js build transpile: { transpile: [ '@inkline' ]}
- I've downgraded Nuxt.js and other dependencies.
- I've cleared yarn's cache and re-installed dependencies.
- I've removed node_modules and yarn.lock and re-installed dependencies.

![image](https://user-images.githubusercontent.com/12578432/90185476-cd6b3c00-dd84-11ea-8145-9daa11d3fc5c.png)

**Comment by csindy** [comment]
I was able to get @inkline/nuxt client and server to compile successfully using @inkline/nuxt version 2.1.0. Server fails to compile on version 2.1.1 and above.

**Comment by ArchaicMage** [comment]
I was able to get @inkline/nuxt client and server to compile successfully using @inkline/nuxt version 2.1.0. Server fails to compile on version 2.1.1 and above.

**Comment by alexgrozav** [comment]
Hey! I'm looking into it. Thank you for reporting this.

**Comment by alexgrozav** [comment]
This seems to happen only with Node >=13. When running with Node 12 it works properly.

I'll try to see if I can find a workaround. If not, I'll have to remove Optional Chaining altogether from the source code. :(

**Comment by alexgrozav** [comment]
@Atinux, @pi0, do you have any idea?

**Comment by galvez** [comment]
You need https://babeljs.io/docs/en/babel-plugin-proposal-pipeline-operator
