### ISSUE TITLE
SSR support for Tabs component

### ISSUE THREAD

**Issue by VanishMax** [inkline/inkline#197]
* **I'm submitting a:**
    - [x] Feature Request
  
* **Summary**
Tabs component is missing SSR support. Too many contents can be lost and not indexed by search engines, therefore, killing SEO. And it definitely will cause a flash of content after hydrating the client.

* **Can you provide a basic example?** 
It is not so difficult to implement. In the library's API, you just need to allow passing a prop like `options` to the `<i-tabs>` with the list of labels to be rendered initially, and a prop like `active` to the `<i-tab>`. With such data, you will know what to render on the server.

Later, during the component's mounting, you can access DOM and pass labels from `<i-tabs>` to `<i-tab>`, and also get the active label from the tab.

**Comment by alexgrozav** [comment]
Hi @VanishMax ! I'm not sure I understand this correctly. 

You're saying that 
- the `i-tab` children should be hidden unless they have the `active` property 
- the `i-tabs` should render some labels initially

Am I correct? You would need this only if there is a large amount of content inside of the tabs, though? 

From what I know Google is executing JS before the indexing starts, so the actual content would be rendered anyway. Correct me if I'm wrong.

**Comment by VanishMax** [comment]
Hi @alexgrozav!

All I'm telling is that SSR support is important. Will just leave an article as a reference to not create spam in here.

I propose you to turn the JavaScipt off on the demo page of i-tabs. You will see, um, nothing. And this is just because the implementation of tabs relies so much on Mounted hook.

Many people would want to use Nuxt or their own SSR implementation. For such case, there's a need to add static props that will be applied in the initial state. For example, `initial-active` and `initial-labels`...

**Comment by alexgrozav** [comment]
I understand now. I'll work on improving this. Thank you for clearing things up!

Or if you find the time, a PR containing these changes would be more than welcome! :)

**Comment by Eternal-Rise** [comment]
@alexgrozav , looks like it's already done?

**Comment by alexgrozav** [comment]
Yup, this is done in Inkline 3. Thank you for the heads up @Eternal-Rise! :)
