### ISSUE TITLE
i-input-number don't work with validation

### ISSUE THREAD

**Issue by Eternal-Rise** [inkline/inkline#199]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
    use ```i-input-number``` with ```:schema``` 

* **What is the expected behavior?**
   pretty validations like on default i-input
  
* **What is the current behavior?**
  Buttons increase / decrease don't work. After blur lost input

* **Please tell us about your environment:**
nuxt ^2.14.4
@inkline/nuxt ^2.3.0

**Comment by alexgrozav** [comment]
If you have the time, please confirm that this is fixed in Inkline 3.
