### ISSUE TITLE
docs links wrong title

### ISSUE THREAD

**Issue by Eternal-Rise** [inkline/inkline#203]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
1. [https://inkline.io/docs/utilities/position](https://inkline.io/docs/utilities/position)
2. [https://inkline.io/docs/utilities/sizing](https://inkline.io/docs/utilities/sizing)
* **What is the expected behavior?** 
  1. Title must be "Position"
  2. Title must be "Sizing"
* **What is the current behavior?**
  1. Title "Border"
  2. Title "Postion"

**Comment by julianalmandos** [comment]
@alexgrozav @Eternal-Rise I think this has already been solved. I reproduced the steps and everything seems to be working fine!

**Comment by alexgrozav** [comment]
Thank you @julianalmandos for looking into it and @Eternal-Rise for reporting the issue!
