### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [inkline/inkline#207]
* **I'm submitting a:** Feature Request

**Comment by alexgrozav** [comment]
It's definitely happening! At the moment I'm waiting for Nuxt@3 to be released in order to go ahead with upgrading both the library and documentation. There will be many improvements and many things rewritten. 

As soon as the new version of nuxt is out, I'll start the migration process and of course, it would be awesome if you and others would be willing to contribute! :)

**Comment by alexgrozav** [comment]
I've created a draft pull request where you can track the progress being made on Inkline 3 https://github.com/inkline/inkline/pull/217. Feedback is most welcome! 😃

**Comment by alexgrozav-visma** [comment]
Great news everyone! I'm back with an update:
- I'm successfully running a [Vite](https://github.com/vitejs/vite) development server and build workflow.
- We now have a components playground under `src/playground`
- Each component now has an `examples` folder containing examples as separate Vue components, which will be importable inside the documentation, but maintained inside the UI Library
- Color variants and size variants generator has been refactored, following the same pattern, more consistent, using CSS variables. The old `variant` property is now simply `color`
- Refactoring all components to use Mixins only where it was actually necessary, making code easier to follow. Also the `classesProvider` and `attributesProvider` workflow has been removed to eliminate "magic code"
- Currently have all utility classes working and components are done up to `ICard`.

**Comment by alexgrozav** [comment]
Great news everyone! I'm back with an update:
- I'm successfully running a [Vite](https://github.com/vitejs/vite) development server and build workflow.
- We now have a components playground under `src/playground`
- Each component now has an `examples` folder containing examples as separate Vue components, which will be importable inside the documentation, but maintained inside the UI Library
- Color variants and size variants generator has been refactored, following the same pattern, more consistent, using CSS variables. The old `variant` property is now simply `color`
- Refactoring all components to use Mixins only where it was actually necessary, making code easier to follow. Also the `classesProvider` and `attributesProvider` workflow has been removed to eliminate "magic code"
- Currently have all utility classes working and components are done up to `ICard`.
- Color mode can now be selected as `system`, `dark` and `light`
- The internal `$inkline` plugin makes use of composition API

**Comment by alexgrozav** [comment]
**Inkline 3.0.0-beta.5** is out! It's currently in a very good shape. 
- All components have been rewritten and improved
- All components have automatically-generated manifest files describing their internals
- Form validation completely rewritten for better efficiency and reactivity
- Most components have updated documentation (work in progress)
- Select component rewritten to support autocomplete with infinite scrolling
- CSS architecture has been updated to easily implement any design system (documentation work in progress)
- Development server is using vite.js
- Every component has individually importable usage examples as components
- Documentation ready for i18n
- Separated applications into separate repositories to make CI/CD easier
- ... more things that I don't remember :sweat_smile: 
 
Still left to do before release:
- Homepage redesign
- Logo redesign using golden ratio
- Documentation redesign
- Forms documentation
- Validation documentation
- Design system documentation
- Datatable component rewrite
- Rewrite all 1000+ tests
 
If anyone's up to diving into it or contribute in any way, It would be absolutely awesome!

**Comment by kfern** [comment]
@alexgrozav. I can help with testing

**Comment by alexgrozav** [comment]
@kfern That would be amazing!

The documentation for the new version is still work in progress and only available locally. To get it up and running:
- `git clone https://github.com/inkline/inkline.git`
- `npm install`, if you run into issues check https://github.com/vitejs/vite/issues/2433#issuecomment-792914871
- `npm run dev`

The installation / integration steps for the beta version can be found here: https://github.com/inkline/inkline#join-the-beta

Let me know how it goes! :)

**Comment by kfern** [comment]
@alexgrozav. I can't run the tests. Jest is not included in the dev dependencies and the test folder is missing. 

How can I start with tests?

**Comment by alexgrozav** [comment]
@kfern I have to finish migrating/refactoring the tests from the old repository. It's still work in progress.

**Comment by kfern** [comment]
@alexgrozav Can I do something while?

**Comment by alexgrozav** [comment]
At this point, the greatest help would be manual testing. Checking that things are behaving correctly after the major refactoring that I've been doing. 

The second thing would be trying out / working with the new CSS variables design system. Would love some feedback on that!

**Comment by bobmcallan** [comment]
I'd really like to help with the Datatable component rewrite.. I'm migrating from a Bulma/Buefy app to Vue 3/Vite/Inkline. I like your layout and there are few (really) component good libs which are as  clean and easy to use as yours.

**Comment by alexgrozav** [comment]
@bobmcallan Thank you so much for the awesome feedback! The datatable won't be a part of the initial release, but as soon as I start development on it, I'll create tasks that you'll be able to help with. :)

**Comment by alexgrozav** [comment]
🚀 Inkline 3 (https://inkline.io) is now officially released! 

Thank you everyone for your support and patience. ❤️

**Comment by tudorels** [comment]
- Hello, I can't find DataTable in Inkline 3? You gave up rewriting it?
- Thank you!

**Comment by alexgrozav** [comment]
Hi @tudorels. I'm planning to do a full rewrite of the Datatable component instead of migrating it. I've created a task to track progress here: https://github.com/inkline/inkline/issues/262
