### ISSUE TITLE
Possible Sass error in IInput/css/_variants.scss file

### ISSUE THREAD

**Issue by Hextar** [inkline/inkline#219]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
    The bug appear while using vuepress (1.8.2). Already tried to downgrade to sass-loader@10 as stated in [that commit](https://github.com/inkline/inkline/commit/c50032269c6bc506b3351315c26ea2c216f46e7e).

* **What is the expected behavior?** 
  The project should work, also with no console errors
  
* **What is the current behavior?**
While running with 'vuepress dev src' a project the initial page is shown blank and in the console appear an error message related to an IInput sass error

* **Please tell us about your environment:**
  - Version: 2.3.1
  - Browser: [all]
  - Language: [ES6/7]

* **Other information** 
    The IInput error:
    
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: argument `$map` of `map-get($map, $key)` must be a map
        on line 5 of node_modules/@inkline/inkline/src/components/IInput/css/_variants.scss, in function `map-get`
        from line 5 of node_modules/@inkline/inkline/src/components/IInput/css/_variants.scss
        from line 8 of node_modules/@inkline/inkline/src/components/IInput/style.scss
        from line 26 of src/.vuepress/styles/index.scss
>>     $_color: map-get($variant, 'color');
```
Also in that file there is probably a typo, cause in the first comment of the page there is  'Navbar variants' instead of 'Input variants'

**Comment by alexgrozav** [comment]
Might be related to a previous issue. What sass-loader version are you using?

**Comment by vonWolfehaus** [comment]
I created a new project with vue-cli and using nightwatch for e2e testing, but it calls out 33 sass-related errors when trying it. I tried installing sass-loader@10 but that did nothing (currently it's at 10.1.1) and node-sass v5.0

I'll print out the first error but the second error was what most of them comprise of.
```
error  in ./node_modules/@inkline/inkline/src/components/IRadioButton/style.scss?vue&type=style&index=0&id=3ede9fdc&lang=scss&scoped=true&     

SassError: ("xs": 0.6, "sm": 0.8, "md": 1, "lg": 1.2, "xl": 1.4) isn't a valid CSS value.
   ╷
12 │ $button-padding: size-map($button-padding-base, $sizes, $size-multipliers) !default;
   │                                                         ^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@inkline\inkline\src\components\IButton\css\_variables.scss 12:57  @import
  C:\Users\Corey.Birnbaum\Documents\GitHub\recruiting-portal\node_modules\@inkline\inkline\src\components\IRadioButton\style.scss 2:9
                                                            root stylesheet


 @ ./node_modules/@inkline/inkline/src/components/IRadioButton/style.scss?vue&type=style&index=0&id=3ede9fdc&lang=scss&scoped=true& 1:0-391 1:0-391
 @ ./node_modules/@inkline/inkline/src/components/IRadioButton/index.vue
 @ ./node_modules/@inkline/inkline/src/components/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```
```
error  in ./node_modules/@inkline/inkline/src/components/IAlert/style.scss?vue&type=style&index=0&id=679778e3&lang=scss&scoped=true&

SassError: compound selectors may no longer be extended.
Consider `@extend .alert, .-md` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
55 │     @extend .alert.-md;
   │             ^^^^^^^^^^
   ╵
  C:\Users\Corey.Birnbaum\Documents\GitHub\recruiting-portal\node_modules\@inkline\inkline\src\components\IAlert\style.scss 55:13  root stylesheet


 @ ./node_modules/@inkline/inkline/src/components/IAlert/style.scss?vue&type=style&index=0&id=679778e3&lang=scss&scoped=true& 1:0-391 1:0-391   
 @ ./node_modules/@inkline/inkline/src/components/IAlert/index.vue
 @ ./node_modules/@inkline/inkline/src/components/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by alexgrozav** [comment]
It looks like there have been some changes in `node-sass` and `sass-loader`. To solve the issue, versions need to remain as follows:

~~~
"node-sass": "<5.0.0",
"sass-loader": "<11.0.0"
~~~

Unfortunately migrating to the new version would require rewriting most of the stylesheet codebase because it relies on extending composed selectors. This will be fixed in `inkline@3`.
