### ISSUE TITLE
Select Button

### ISSUE THREAD

**Issue by milaan-muc** [inkline/inkline#230]
* **I'm submitting a:**
    - [x] Feature Request
  
* **Summary**
    A select menu where the selected item is actually a button which can be clicked. Or a button where you can change the action when clicking it.

* **Can you provide a basic example?** 
Example from Zendesk Ticketsystem
![image](https://user-images.githubusercontent.com/3469112/118359682-e6f41b00-b584-11eb-909a-3bed84194a59.png)

* **Motivation**
    Example: Button default action is "Save" but you can also change the behavior to "Save As" to make a copy.

**Comment by alexgrozav** [comment]
@milaan-muc I've put together an example for achieving this with the currently available features. 

https://jsfiddle.net/kwgdo2y1/2/

It's not perfect, but it'll work well. Let me know if you need more help with this. :)
