### ISSUE TITLE
onChange Event not working with Select

### ISSUE THREAD

**Issue by milaan-muc** [inkline/inkline#231]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
    When using `<i-select @change="function"> ` the linked function is not fired upon change event. If using a default select menu, it is working.

**Comment by alexgrozav** [comment]
You'll need to use the `@input` instead, since it's configured to work with `v-model`. Can you try and let me know if it works?

**Comment by milaan-muc** [comment]
> You'll need to use the `@input` event instead, since it's configured to work with `v-model`. Can you try and let me know if it works the way you expect it to?

Working. Thank you.
