### ISSUE TITLE
Make use of defaultOptions to set default components sizes

### ISSUE THREAD

**Issue by calebeaires** [inkline/inkline#233]
* **I'm submitting a:**
    - [x] Feature Request
  
* **Summary**
   Make use of defaultOptions to set default size

* **Can you provide a basic example?** 

At setup:

```js

app.use(Inkline, {
    components: {
        ICheckbox,
        ICard, IButton, IForm, IInput, IFormGroup, IFormLabel, IContainer, IColumn, IRow
    }
    config: {
         variant: 'light',
         size: 'sm', // <====

     }
})

```

Usage at components
```js
        /**
         * @description The size variant of the button
         * @type sm | md | lg
         * @default md
         */
        size: {
            type: String,
            default: defaultOptions.size, // <=== 
            validator: sizePropValidator
        }
```

* **Motivation**
    In many cases our project follows some defaults to all components. Ex.: button and inputs with size 'sm'. It will be useful to have this set at the setup.

**Comment by alexgrozav** [comment]
Great suggestion! I'll see how I can implement this.

**Comment by alexgrozav** [comment]
Done in `3.0.0-beta.8`. You can now set default size and color for all components or individual components using the following options:

~~~
app.use(Inkline, {
    components: { ... },
    color: 'light',
    size: 'sm',
    componentOptions: {
        IButton: {
            color: 'primary',
            size: 'lg'
        }
    }
}) 
~~~

**Comment by calebeaires** [comment]
This is good! Thank you so much!

**Comment by alexgrozav** [comment]
Thank you for the suggestion. Enjoy! :)
