### ISSUE TITLE
Vue 3 / Vite - No Colors ?

### ISSUE THREAD

**Issue by bobmcallan** [inkline/inkline#238]
I've installed as per instructions,. however no colors are showing. 

`
import '@inkline/inkline/src/inkline.scss';

import { Inkline } from '@inkline/inkline/src';

import * as components from '@inkline/inkline/src/components';

import * as icons from '@inkline/icons/packs/inkline';
`

![image](https://user-images.githubusercontent.com/8773580/120789371-e2fc5d00-c574-11eb-8536-523d704c7377.png)

There is no other style/css/scss or variable replacement. Straight install as per doco.

**Versions**
`
        "@inkline/inkline": "^3.0.0-beta.6",

        "browser-bunyan": "^1.6.3",

        "install": "^0.13.0",

        "jwt-decode": "^3.1.2",

        "luxon": "^1.27.0",

        "mande": "^1.0.0",

        "mitt": "^2.1.0",

        "pinia": "^2.0.0-beta.2",

        "vue": "^3.1.0-beta.7",

        "vue-class-component": "^8.0.0-rc.1",

        "vue-router": "^4.0.8"
`

**Comment by bobmcallan** [comment]
I should have read all (!) the Vue 3 thread..  Swapping 'variant' to 'color' does the trick!

**Comment by alexgrozav** [comment]
@bobmcallan I thought it makes more sense to use `color` from a Developer Experience point of view. How do you feel about it?
