### ISSUE TITLE
Feature Request: Make i-select value/v-model as simple as possible at V3

### ISSUE THREAD

**Issue by calebeaires** [inkline/inkline#240]
* **I'm submitting a:**
    - [x] Feature Request
  
* **Summary**
Version 3 offers a type of "select" where the defined value is an object. This context is excellent, however, it is necessary in many cases that in a simple action the option value attribute is the one that is selected. As it stands today, we have to build a much larger code than usual to apply to our context.

* **Can you provide a basic example?** 
The code above is from the previous version. Have the "selected.value" equals the selected make things much more easier
```vue
<i-select v-model="selected.value" placeholder="Choose an option">
    <i-select-option value="a" label="Option A" />
    <i-select-option value="b" label="Option B" />
    <i-select-option value="c" label="Option C" />
    <i-select-option value="d" label="Option D" disabled />
</i-select>
```

* **Motivation**
    Do more with less!

**Comment by alexgrozav** [comment]
I've released a fix that provides backwards-compatible behaviour in `3.0.0-beta.7`. Cheers! :)
