### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Himra** [inkline/inkline#252]
Hello all,

I am looking for an autocomplete field for my form.
I searched the documentation for it but couldn't find anything.
Is there a solution, or is something planned for this?

Thanks and greetings
Himra

**Comment by alexgrozav** [comment]
Hi Himra,

There is a fully functional select component with autocomplete in the `3.0.0-beta.44` beta version. The full release together with the documentation will come in a few days. 

If you want to use the version 3 beta, there's a Storybook temporarily published [here](https://inkline-storybook-fcrak.ondigitalocean.app/storybook). The documentation for the select can be found here for now: https://github.com/inkline/inkline.io/tree/main/src/pages/docs/forms/select

**Comment by Himra** [comment]
Thank you for the quick answer and the great project
Himra
