### ISSUE TITLE
Creating Vue App with Vue CLI results in `module parse fail`

### ISSUE THREAD

**Issue by agarbutt** [inkline/inkline#257]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
Here is a minimal repository (and ordered commits) showing the steps that I took.

https://github.com/agarbutt/vue-cli-ts-inkline

1. follow the "Vue CLI Getting started instructions"
2. `npm run serve`

* **What is the expected behavior?** 
I believe we expect to have a running Vue app.
  
* **What is the current behavior?**
Multiple compiler failures from webpack.  It seems to fail when loading / parsing the components provided in the package `@inkline/inkline`

* **Please tell us about your environment:**
  - Version: 3.0.6
  - Browser: [n/a]
  - Language: [TypeScript ~4.1.5 | ES6/7 ]
  - Vue CLI: `@vue/cli 4.5.15`
  - Vue: `vue@3.2.27`

* **Other information** 
    Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.

This is an example of the errors dumped to the console.
`
 error  in ./node_modules/@inkline/inkline/components/IDropdown/components/IDropdownItem/script.mjs?vue&type=script&lang=js

Module parse failed: Unexpected token (88:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     methods: {
|         onClick(event) {
>             this.dropdown.onItemClick?.(this, event);
|         }
|     }

 @ ./node_modules/@inkline/inkline/components/IDropdown/components/IDropdownItem/script.mjs?vue&type=script&lang=js 1:0-65 1:0-65 1:66-120 1:66-120
 @ ./node_modules/@inkline/inkline/components/IDropdown/components/IDropdownItem/index.vue
 @ ./node_modules/@inkline/inkline/components/IDropdown/components/index.mjs
 @ ./node_modules/@inkline/inkline/components/index.mjs
 @ ./node_modules/@inkline/inkline/inkline.mjs
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.10:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
`

**Comment by alexgrozav** [comment]
Hi @agarbutt, thank you for reporting this! I'm looking into it and will provide an update today.

**Comment by alexgrozav** [comment]
Hey @agarbutt, I've updated the [Vue.js 3 CLI installation guide](https://inkline.io/docs/introduction/installation/vue-cli). Thank you for your patience and for reporting the issue!

**Comment by alexgrozav** [comment]
@all-contributors please add @agarbutt for bug.

**Comment by agarbutt** [comment]
@alexgrozav I have tried the CLI instructions and I am getting a similar (if not the same) error. 

I have updated the git repository mentioned above with the changes introduced from following the CLI instructions. 

https://github.com/agarbutt/vue-cli-ts-inkline

Running `npm run serve` which is a proxy for `vue-cli-service serve`, I get errors when "loading" the following components.

- IDropdownItem/script.mjs
- IFormLabel/script.mjs
- IIcon/script.mjs
- mixins/props/default.mjs
- ISelect/script.mjs
- IInput/script.mjs
- INumberInput/script.mjs
- ICheckbox/script.mjs
- IRadio/script.mjs
- IToggle/script.mjs
- IForm/script.mjs
- ICheckboxGroup/script.mjs
- IRadioGroup/script.mjs
- IFormGroup/script.mjs

Here is an example error message for the `IFormGroup/script.mjs`:

```
 error  in ./node_modules/@inkline/inkline/components/IForm/components/IFormGroup/script.mjs?vue&type=script&lang=js

Module parse failed: Unexpected token (107:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     methods: {
|         onBlur(name, event) {
>             this.parent?.onBlur?.(this.name ? `${this.name}.${name}` : name, event);
|         },
|         onInput(name, value) {

 @ ./node_modules/@inkline/inkline/components/IForm/components/IFormGroup/script.mjs?vue&type=script&lang=js 1:0-65 1:0-65 1:66-120 1:66-120
 @ ./node_modules/@inkline/inkline/components/IForm/components/IFormGroup/index.vue
 @ ./node_modules/@inkline/inkline/components/IForm/components/index.mjs
 @ ./node_modules/@inkline/inkline/components/index.mjs
 @ ./node_modules/@inkline/inkline/inkline.mjs
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.100.48:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

Am I missing a config for loading `.mjs` modules? I am sorry if is turning into a support request. 

Global Packages installed (`npm list --depth=0`):
```
├── @vue/cli@4.5.15
└── npm@8.3.2
```

Local packages installed (`npm list --depth=0`):
```
├── @inkline/inkline@3.0.7
├── @types/jest@24.9.1
├── @typescript-eslint/eslint-plugin@4.33.0
├── @typescript-eslint/parser@4.33.0
├── @vue/cli-plugin-e2e-cypress@4.5.15
├── @vue/cli-plugin-eslint@4.5.15
├── @vue/cli-plugin-router@4.5.15
├── @vue/cli-plugin-typescript@4.5.15
├── @vue/cli-plugin-unit-jest@4.5.15
├── @vue/cli-service@4.5.15
├── @vue/compiler-sfc@3.2.27
├── @vue/eslint-config-prettier@6.0.0
├── @vue/eslint-config-typescript@7.0.0
├── @vue/test-utils@2.0.0-rc.18
├── eslint-plugin-prettier@3.4.1
├── eslint-plugin-vue@7.20.0
├── eslint@6.8.0
├── prettier@2.5.1
├── sass-loader@10.2.1
├── sass@1.49.0
├── typescript@4.1.6
├── vue-jest@5.0.0-alpha.10
├── vue-router@4.0.12
└── vue@3.2.27
```

**Comment by alexgrozav** [comment]
@agarbutt Didn't realize that the typescript Vue CLI setup doesn't install babel at all. I solved this by installing babel:

~~~bash
vue add babel
~~~

I'll add this to the docs.

**Comment by agarbutt** [comment]
@alexgrozav , you found the final step. nice job!

Looks like I have some things to read up on why Vue made some of the choices about Babel and Typescript.
Its confusing to me to have both compilers, and I am not totally aware of why one would choose one, the other, or both to be leveraged within a project. 

Thanks for your help.  I am enjoying inkline quite a bit. Perhaps I can start to offer some more support to the community. 

Keep up the nice work.
