### ISSUE TITLE
Not using the semantic tag for the navigation (Accessibility issue)

### ISSUE THREAD

**Issue by masihtak** [inkline/inkline#266]
* **What is the expected and current behavior?**
  Semantic HTML5 `nav` tag is expected.
  The current behavior is just a `div` tag with the class of `navbar` 

* **Steps to reproduce**
  `<i-navbar></i-navbar>`

* **Please tell us about your environment:**
    - Version: >=3.0.0
    - Browser: Chrome 98
    - Language: JavaScript

* **Other information**
  For the navigation currently, we have a none semantic tag, `div` which is a bad practice, not to mention it will also cause some accessibility issues.

  HTML5 defines a `<nav>` menu, which is to be used to contain the primary navigation of a website. 
According to the WCAG 2.0 gridlines: 
"If you have to use more generic elements such as a `div`, add `role="navigation"` to every navbar to explicitly identify it as a landmark region for users of assistive technologies", inkline currently does `role="navigation"` but using `nav` and lists to create menus is great for several reasons:

- It is easy to differentiate the primary navigation lists/links from other lists and links on the page because they are the ones inside the `<nav>`. Not only will this make finding it easier for screen reader users, as mentioned above, but it makes targeting it with CSS and JavaScript easier too.

- Lists can be nested, which means you can easily create several levels of navigation hierarchy.

- Even without any styling applied to the list, the browser rendering of the HTML makes sense and it is easy to grasp for a visitor that these links belong together and make up one logical unit.

[More info](https://www.w3.org/community/webed/wiki/Creating_multiple_pages_with_navigation_menus)

**Comment by alexgrozav** [comment]
Hey @masihtak, thank you for the great suggestion! Do you have the time to create a PR with the changes?

**Comment by masihtak** [comment]
Yes, please assign me to this issue.
