### ISSUE TITLE
Condensed table have same spacing as regular table [Firefox]

### ISSUE THREAD

**Issue by Extarys** [inkline/inkline#272]
* **What is the expected and current behavior?**
I expect the condensed table to fit more data on smaller screen. ie: margin/padding and text is smaller.

Right now there is no difference.

* **Steps to reproduce**
[  If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.]

https://stackblitz.com/edit/inkline-d84znh?file=src/App.vue

* **Please tell us about your environment:**
    - Version:     "@inkline/inkline": "^3.0.8",  "@inkline/nuxt": "^3.0.5",
    - Browser: Firefox 99.0a1
    - Language: all

* **Other information**
![image](https://user-images.githubusercontent.com/11581433/156675768-d0554922-d43f-4474-83c0-928efa456908.png)

Current CSS rules for the .condensed table are:
```
.table-wrapper.-condensed .table th, .table-wrapper.-condensed .table td {
  ----padding: var(----padding--condensed);
}
----padding-top--condensed: calc(var(--padding-top) * 1 / 4);
----padding-right--condensed: calc(var(--padding-right) * 1 / 4);
----padding-bottom--condensed: calc(var(--padding-bottom) * 1 / 4);
----padding-left--condensed: calc(var(--padding-left) * 1 / 4);
----padding--condensed: var(----padding-top) var(----padding-right) var(----padding-bottom) var(----padding-left);
```

**Comment by alexgrozav** [comment]
HI @Extarys, thank you for reporting this. I'll take some time to fix it over the weekend! :)

**Comment by Extarys** [comment]
Thanks @Eternal-Rise
Closing as fixed.
