### ISSUE TITLE
Core Layout for content and right aside is not responsive on mobile 

### ISSUE THREAD

**Issue by fmedinar** [inkline/inkline#276]
**What is the expected and current behavior?**
The behavior por core-layout is not responsive on mobile for content and left or right aside. The other components are distorted.

* **Steps to reproduce**
Copy and paste layout with header, content, right aside componentes and simulate mobile access in the explorer.

* **Please tell us about your environment:**
    - Version: >=3.0.0
    - Browser: all
    - Language: vuejs

* **Other information**
NA

**Comment by alexgrozav** [comment]
Responsiveness for layout content + aside is supposed to be handled by the user. You can use the `ISidebar` component for out of the box responsive behaviour.
