### ISSUE TITLE
Unit testing components with cypress

### ISSUE THREAD

**Issue by jb3rndt** [inkline/inkline#278]
* **What is the expected and current behavior?**
  I want to unit test components that use Inkline components. In the interactive browser test runner of cypress, my custom component should look like a normal Inkline button as it does in the web app. Instead, the button is unstyled. How can I get cypress to recognize the scss styles of Inkline?

Additionally, Inkline has to be registered as a plugin for each component that is mounted in the tests. That leads to cypress fetching the whole Inkline package from the local fs which takes ~10s for every test. That makes the interactive test runner practically useless. How would that be done correctly?

* **Steps to reproduce**
MyButton component
```ts
<script lang="ts">
import { defineComponent } from "vue";
import "@inkline/inkline/inkline.scss";
import "@/assets/base.scss";

export default defineComponent({
  props: {
    label: { type: String, required: true },
  },
});
</script>

<template>
  <i-button>
    {{ label }}
  </i-button>
</template>
```
MyButton.spec.ts
```ts
import { mount } from "@cypress/vue";
import MyButton from "@/components/MyButton.vue";
import { Inkline } from "@inkline/inkline";

describe("My Button", () => {
  it("exists", () => {
    mount(MyButton, {
      global: {
        plugins: [Inkline],
      },
      props: {
        label: "Test",
      },
    });
  });
});
```
Result: 
![grafik](https://user-images.githubusercontent.com/45318735/163978287-9ceaa2b3-bd95-400e-9517-b9c977178dae.png)

* **Please tell us about your environment:**
    - Version: >=3.0.0
    - Browser: Chrome 100.0.4896.88
    - Language: TypeScript
    - Vue3 3.2.31, Vite 2.8.4, Cypress 9.5.0

**Comment by alexgrozav** [comment]
Hey @jb3rndt, instead of importing your scss (i.e. `inkline.scss`) in every component, you should import them globally in your `main.ts` file. Otherwise, the scss will get recompiled every time this component changes and it will add up to a lot of build time.

Next, to import them to cypress globally, add them to `./cypress/support/index.ts`. 

Unforunately, Inkline still needs to be registered as a plugin. I'm not familiar enough with Cypress to know if there's a way to register globally, but there might be. 

Let me know if the issue still presists after moving the imports.

**Comment by jb3rndt** [comment]
Sadly I did not find much help there. I can verify that custom scss is loaded, but the scss imported from the inkline module is not. Might be an issue on the cypress side, I don't know.

But I found another issue.
Here is a basic sfc using `i-modal`:
`MyModal.vue`
```
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({});
</script>

<template>
  <i-modal size="lg" color="warning">
    <template #header>Modal Header</template>
    Modal content
    <template #footer>Modal Footer</template>
  </i-modal>
</template>
```
`MyModal.spec.ts`
```
import { mount } from "@cypress/vue";
import MyModal from "@/components/MyModal.vue";
import { Inkline } from "@inkline/inkline";

describe("Button", () => {
  it("exists", () => {
    mount(MyModal, {
      global: {
        plugins: [Inkline],
      },
      props: {
        isAttentive: true,
        isTrained: true,
      },
    });
  });
});
```

As it turns out, only the "Modal content" is rendered in the cypress view. Do you know why that happens? (wrapping header and footer content inside `<p>` does not change it.
![grafik](https://user-images.githubusercontent.com/45318735/164325543-d5c93017-a36d-43ff-a0af-15057d876d32.png)
