### ISSUE TITLE
createPopper issue

### ISSUE THREAD

**Issue by R0N1n-dev** [inkline/inkline#281]
* **What is the expected and current behavior?**
  Added Inkline 3 to vue cli project with Vue 3. 
On "npm run serve", should run the dev server .
But instead give this error  and dev server wont start

 "ERROR  Failed to compile with 1 error                                 10:01:21 AM

 error  in ./node_modules/@inkline/inkline/mixins/PopupMixin.mjs

Can't import the named export 'createPopper' from non EcmaScript module (only default export is available)"

* **Steps to reproduce**
 -Scaffold a Vue 3 project with defaults using Vue-Cli(v4)
-Add inkline3 as stated in the installation instructions for Vue Cli on the installation page.(Added imports to main.js, added main.scss, 

* **Please tell us about your environment:**
* OS: Zorin 16 lite
    - npm v8.5.5
    - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
    - Language: [Vue/ ES]

* **Other information**
  Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.

**Comment by alexgrozav** [comment]
Hey! I just created a new project using Vue CLI 5 and I'm not having the issue. Do you have something else installed that requires a different popper.js version that might be interfering?

Could you try to clean up your dependencies and reinstall, then run again? 

~~~bash
rm -r node_modules
npm install
npm run serve
~~~

**Comment by alexgrozav** [comment]
Closing until further feedback.
