### ISSUE TITLE
Usage of form validation with field types other than `<i-input>` and `<i-textarea>`

### ISSUE THREAD

**Issue by intjelic** [inkline/inkline#287]
I used form validation successfully in my previous forms, but now I'm working with a form that has more than `<i-input>` and `<i-textarea>` field types.

I can get my `<i-select>` field type to work in my form, but as soon as I had the `v-model` to `<i-form>` (to add validation of text fields), the `<i-select>` no longer works. 

Is this scenario supported ? How am I supposed to implement this ?

**Comment by alexgrozav** [comment]
Hi @intjelic, it's likely a bug. Can you share your validation schema and markup so I can test it out properly? Thank you! :)

**Comment by michael-aranea** [comment]
I have the same issue with nuxt3, here is my sample coding:
**Template:**
<i-form v-model="form">
    <i-form-group>
      <i-form-label>{{ $t("gender") }}</i-form-label>
        <i-select
            name="gender"
            :options="genders"
        />
      <i-form-error for="gender" :visible="['invalid']" />
    </i-form-group>
  </i-form>

**Script:**
<script setup lang="ts">
const schema = initialize({
    gender: {
      validators: [
        {
          name: "required",
          message: this.t("requiredValidation"),
        },
      ],
    },
  });

  const form = reactive(schema);

  const genders = reactive([{id: 'male', label: t('male')}, {id: 'female', label: t('female')}])
</script>

**Comment by alexgrozav** [comment]
Should be fixed in v4.4.0
