### ISSUE TITLE
click-outside - mouseup vs mousedown

### ISSUE THREAD

**Issue by tasiotas** [inkline/inkline#296]
Currently click-outside Directive is firing on `mouseup` event. That is causing some unexpected behavior in Modal.
When I drag-select input field in modal, and release mouse button outside the modal, it closes.
  
Perhaps you could consider switching to 'mousedown' event?
  
Thank you

**Comment by DenisJankelaic** [comment]
Stumbled upon same issue. Would be nice to be adjusted.

**Comment by alexgrozav** [comment]
Fixed in #319. Released under version `3.1.6`.

Please try it out and confirm that it works for your use case as well. :)

**Comment by tasiotas** [comment]
thank you, works well
