### ISSUE TITLE
Sizing of iButtonGroup doesn't work

### ISSUE THREAD

**Issue by joewelds** [inkline/inkline#298]
* **What is the expected and current behavior?**
Actual behavior:  Buttons in the button group are medium sized
Expected behavior: Buttons adjust size when the size="sm" is set on the iButtonGroup element

* **Steps to reproduce**
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
[See that buttons are not different sizes in the Size Variants example.](https://www.inkline.io/docs/components/button-group#size-variants) 

* **Please tell us about your environment:**
    - Version: "vue": "^3.2.37", "@inkline/inkline": "^3.0.9"
    - Browser: Chrome 103.0.5060.66 | Firefox 102.0 (64-bit) 

* **Other information**
![image](https://user-images.githubusercontent.com/28027932/177626052-7a24efd6-7cd3-4b15-823d-24aa14fe9b72.png)

**Comment by alexgrozav** [comment]
Fixed in v4.
