### ISSUE TITLE
Can't import a single component 

### ISSUE THREAD

**Issue by joewelds** [inkline/inkline#300]
* **What is the expected and current behavior?**
I followed the code on the vite and plugin config documentation pages: 
https://www.inkline.io/docs/introduction/installation/vite
https://www.inkline.io/docs/introduction/plugin-options

* **Steps to reproduce**
Try to import a single component with main.js similar to noted code on plugin options page of docs: 

```
import { IButton } from '@inkline/inkline/components';

app.use(Inkline, {
    components: {
        IButton
    }
});

```

* **Please tell us about your environment:**
    - Version: >=3.0.9
    - Vite: >= 2.9.12
    - @vitejs/plugin-vue >=2.3.3
    - Language: ES

* **Other information**
![image](https://user-images.githubusercontent.com/28027932/178966063-abfafc1d-fb56-4fdf-97b1-ef5a8d706558.png)

**Comment by alexgrozav** [comment]
Hello! Thank you for reporting this. Looks like the latest `vite` had some internal changes. Individual importing should work out of the box now, with the latest Inkline version.

**Comment by alexgrozav** [comment]
@all-contributors Add @joewelds for bug.
