### ISSUE TITLE
Clearable doesnt appear right

### ISSUE THREAD

**Issue by R0N1n-dev** [inkline/inkline#304]
The clearable icon on the input component does not render properly, in development or production
Only works fine in Firefox

* **Steps to reproduce**
  Add clearable option to input

* **Please tell us about your environment:**
    - Version: >=3.0.0
    - Browser: [Brave 1.41  and Chrome 104 ]
    - Language: [all | JavaScript | ES]

package.json
{
  "name": "vite-vue3",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@inkline/inkline": "^3.0.9",
    "firebase": "^9.9.0",
    "pinia": "^2.0.14",
    "remixicon": "^2.5.0",
    "vue": "^3.2.25",
    "vue-router": "^4.1.1"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.0",
    "sass": "^1.53.0",
    "unplugin-vue-components": "^0.21.0",
    "vite": "^3.0.0"
  }
}
![Screenshot_2022-07-31_14-21-47](https://user-images.githubusercontent.com/83344872/182024134-82b7ad5c-76c1-4067-aefc-7b105b3af185.png)

firefox

![Screenshot_2022-07-31_14-30-46](https://user-images.githubusercontent.com/83344872/182024227-7c65ce03-c579-4c28-9e6f-8481519ae246.png)

**Comment by alexgrozav** [comment]
Working properly in v4.
