### ISSUE TITLE
Does not start with Nuxt 3 rc.10 [Failed to parse source for import... add "**/*.html?v=841df9b4" to `assetsInclude` in your configuration.]]

### ISSUE THREAD

**Issue by Nobi322** [inkline/inkline#312]
* **What is the expected and current behavior?**
Project dos not start when Inkline is present in package, seems that related with autoImports, that was deprecated in nuxt rc.9

* **Steps to reproduce**
  Update to Nuxt RC.10 (edge.rc.11 have same problem)

* **Please tell us about your environment:**
    "@inkline/nuxt": "^3.1.4",
    "nuxt": "3.0.0-rc.10",

* **Other information**
  ` ERROR  08:49:35 [vite] Internal server error: Failed to parse source for import analysis because th
e content contains invalid JS syntax. You may need to install appropriate plugins to handle the .htm
l?v=841df9b4 file format, or if it's an asset, add "**/*.html?v=841df9b4" to assetsInclude in your c
onfiguration.
  Plugin: vite:import-analysis
  File: C:/WORK/nuxt3-app/node_modules/.pnpm/@inkline+inkline@3.1.4_vue@3.2.39/node_modules/@inkline
/inkline/components/IForm/components/IFormGroup/template.html?v=841df9b4
  4  |       role="group">
  5  |      <slot />
  6  |  </fieldset>
     |             ^
  7  |
      at formatError (file:///C:/WORK/nuxt3-app/node_modules/.pnpm/vite@3.1.2_sass@1.54.9/node_modul
es/vite/dist/node/chunks/dep-cff57044.js:40841:46)
      at TransformContext.error (file:///C:/WORK/nuxt3-app/node_modules/.pnpm/vite@3.1.2_sass@1.54.9
/node_modules/vite/dist/node/chunks/dep-cff57044.js:40837:19)
      at TransformContext.transform (file:///C:/WORK/nuxt3-app/node_modules/.pnpm/vite@3.1.2_sass@1.
54.9/node_modules/vite/dist/node/chunks/dep-cff57044.js:37508:22)
      at async Object.transform (file:///C:/WORK/nuxt3-app/node_modules/.pnpm/vite@3.1.2_sass@1.54.9
/node_modules/vite/dist/node/chunks/dep-cff57044.js:41090:30)
      at async loadAndTransform (file:///C:/WORK/nuxt3-app/node_modules/.pnpm/vite@3.1.2_sass@1.54.9
/node_modules/vite/dist/node/chunks/dep-cff57044.js:37351:29)`

![image](https://user-images.githubusercontent.com/6026022/190964166-57a7fea8-172a-43d1-9fa2-e368ec828433.png)

**Comment by Nobi322** [comment]
Is here anybody to answer?

**Comment by alexgrozav** [comment]
Hey! I'm looking into it. Thank you for reporting the issue.

**Comment by alexgrozav** [comment]
I'm unable to reproduce this. I've just created a clean Nuxt 3.0.0-rc.11 app and it seems to be working without issues. Can you try to reinstall your dependencies? `rm -r node_modules .nuxt && npm install`

If it's still not working, can you provide a minimal reproduction repo or steps?

**Comment by Nobi322** [comment]
Hey @alexgrozav thanks for reply! I tried to prepare reproduction, bet seems on stakblitz it works ok. Also fresh install locally was made, tried both npm and pnpm. Same result. Even cleaned project from all other pages/components/modules e.t.c. But same rerulst, in moment when I add any Inkline component it starts to throw errors.

Here is reproduction on stackblitx, it doesn't throw errors, but have same dependencies as my project. https://stackblitz.com/edit/nuxt-starter-g1p165?file=layouts/default.vue

` ERROR  11:30:49 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Yo
u may need to install appropriate plugins to handle the .html?v=7f6a191d file format, or if it's an asset, add "**/*.html?v=7f6a191d" to ass
etsInclude in your configuration.
  Plugin: vite:import-analysis
  File: C:/WORK/nuxt3-app/node_modules/@inkline/inkline/components/ILoader/template.html?v=7f6a191d
  2  |      <span v-if="$slots.default" class="loader-text">
  3  |          <slot />
  4  |      </span>
     |             ^
  5  |      <svg viewBox="25 25 50 50">
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/ILoader/template.html"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IModal/template.html?import&v=7f6a
191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IModal/template.html?import&v=7f6a
191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IModal/template.html?import&v=7f6a
191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IModal/template.html"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IButton/template.html?import&v=7f6
a191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IButton/template.html?import&v=7f6
a191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IButton/template.html?import&v=7f6
a191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/IButton/template.html"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/ILoader/template.html?import&v=7f6
a191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/ILoader/template.html?import&v=7f6
a191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/ILoader/template.html?import&v=7f6
a191d"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@inkline/inkline/components/ILoader/template.html"`

**Comment by alexgrozav** [comment]
Could be that it only happens on Windows. I'll try a Windows machine tomorrow to see what happens.

**Comment by Nobi322** [comment]
> Could be that it only happens on Windows. I'll try a Windows machine tomorrow to see what happens.

I tried exact same code that fails on Windows machine, in Ubuntu virtual machine. And it's works. Now need to understand who is responsible for that.

**Comment by Feelixe-tin** [comment]
I have the same problem on a fresh project. Also running Windows.

**Comment by alexgrozav** [comment]
I've created an issue in the `nuxt/framework` repository. Seems to be related to referencing `html` files in the latest Nuxt version. I'm sorry guys!

Meanwhile, until it's fixed, you could create a Nuxt plugin manually:

`plugins/inkline.ts`
~~~
import { Inkline, components } from '@inkline/inkline';
import '@inkline/inkline/inkline.scss';

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(Inkline, { components });
});
~~~

**Comment by Nobi322** [comment]
@alexgrozav thanks for help!

**Comment by danielroe** [comment]
Looking into this, this is not an issue with Nuxt, but is coming from Vite's import analysis plugin.

Here's a pure Vite reproduction - https://stackblitz.com/edit/github-kurrn8 - download that on Windows and you should see the same error that you're getting here. I'd suggest raising on https://github.com/vitejs/vite.

**Comment by alexgrozav** [comment]
Thanks a lot for the help, @danielroe. 

I've opened up an issue on the Vite repo: https://github.com/vitejs/vite/issues/10278

**Comment by vecter** [comment]
> I've created an issue in the `nuxt/framework` repository. Seems to be related to referencing `html` files in the latest Nuxt version. I'm sorry guys!
> 
> Meanwhile, until it's fixed, you could create a Nuxt plugin manually:
> 
> `plugins/inkline.ts`
> 
> ```ts
> import { Inkline, components } from '@inkline/inkline';
> import '@inkline/inkline/inkline.scss';
> 
> export default defineNuxtPlugin(nuxtApp => {
>   nuxtApp.vueApp.use(Inkline, { components });
> });
> ```

Thanks for this snippet. Why does creating a plugin resolve this issue?

**Comment by Kiptoke** [comment]
Hey @alexgrozav - I noticed your [opened Vite issue](https://github.com/vitejs/vite/issues/10278) was resolved a couple days ago - do you know when that resolution should help resolve this issue?
