### ISSUE TITLE
Form validation entirely non funcitonal

### ISSUE THREAD

**Issue by then3rdman** [inkline/inkline#313]
* **What is the expected and current behavior?**
Validation is completely broken. 

![CleanShot 2022-10-03 at 16 29 28](https://user-images.githubusercontent.com/10450280/193507274-cd02430b-d84e-4f6a-8c76-8d7f15cb9b30.png)

* **Steps to reproduce**
[Reproduction](https://stackblitz.com/edit/vitejs-vite-mcraqu?file=src/App.vue)

* **Please tell us about your environment:**
    - Version: 3.1.4
    - Browser: all
    - Language: TypeScript

* **Other information**
I have tried both options and composition api, and multiple difrent apporaches but all result in the same errors.

**Comment by alexgrozav** [comment]
Hi @then3rdman! The form validation needs to create the connection between the form schema data key and the actual input field. To achieve this, you'll need to provide a `name` to your input (in this case, `username`).

https://stackblitz.com/edit/vitejs-vite-lnpdjm?file=src%2FApp.vue

**Comment by then3rdman** [comment]
appologies, I had been playing with the stackblitz and accidently saved the changes. 

Have changed to be what it should be and the error is now there. It would seem to only occure when using `script setup`

**Comment by alexgrozav** [comment]
Alright, thanks for the update. Looking into it.

**Comment by alexgrozav** [comment]
Hey! I've released version `3.1.5`, which should fix the issue you're having. Can you please confirm?

To be honest I haven't done much extensive testing for the `useForm` helper (most of my application code is still using options API, until I get the time to refactor it), so please, if you find any issue, make sure to report it and I'll get it fixed asap. 🙏

**Comment by then3rdman** [comment]
Working correctly now!

**Comment by zozulinskyi** [comment]
> Hey! I've released version `3.1.5`, which should fix the issue you're having. Can you please confirm?
> 
> To be honest I haven't done much extensive testing for the `useForm` helper (most of my application code is still using options API, until I get the time to refactor it), so please, if you find any issue, make sure to report it and I'll get it fixed asap. 🙏

@alexgrozav hi. i have the same problem but with i-select
