### ISSUE TITLE
Dropdown on hover closes on mouseout

### ISSUE THREAD

**Issue by tasiotas** [inkline/inkline#314]
When dropdown component is triggered by hover, it closes as soon as mouse leaves triggering element, before it manages to reach dropdown body container.

Issue visible on docs page
https://www.inkline.io/docs/components/dropdown

thank you

**Comment by alexgrozav** [comment]
Fixed in #319. Released under version `3.1.6`.

Please try it out and confirm that it works for your use case as well. :)
