### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by elrumo** [inkline/inkline#334]
* **What is the expected and current behavior?**
Whenever I add an inkline element to my project I get the following errors below, and nothing shows up on screen. To
`
Uncaught TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js?v=543014ca:2984:34)
    at Proxy.render (index.vue:24:9)
    at renderComponentRoot (runtime-core.esm-bundler.js:898:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5631:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5759:9)
    at mountComponent (runtime-core.esm-bundler.js:5541:9)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
`

`[Vue warn]: Unhandled error during execution of render function 
  at <IToggle modelValue=true onUpdate:modelValue=fn > 
  at <App>`

<img width="682" alt="image" src="https://user-images.githubusercontent.com/36299870/207841389-0772c4c2-8b46-4bf3-ba7c-a006b2c9afa6.png">

* **Steps to reproduce**
I started getting this error on an existing project, so I created a brand new project using vite, and the error persists.
    - Create a new project using the vite CLI.
    - Add inkline.
    - Run "npm run dev" and the error will show up on the browser console.

* **Please tell us about your environment:**
    - Version: >=3.0.0
    - Browser: [all ]
    - Language: [ES] (I have not tried with TS)

package.json: 
```
{
  "name": "test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@inkline/inkline": "^3.1.9",
    "vue": "^3.2.45"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "sass": "^1.56.2",
    "vite": "^4.0.0"
  }
}
```

* **Other information**
  Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.

**Comment by elrumo** [comment]
I've tried to recreate the issue with vie 3.2.5 and it doesn't happen. So I believe the problem must be with vite <4.x.x

```
{
  "name": "test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@inkline/inkline": "^3.1.9",
    "vue": "^3.2.38",
    "vue-router": "^4.1.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.2.0",
    "sass": "^1.56.2",
    "vite": "^3.2.5"
  }
}

```

**Comment by alexgrozav** [comment]
Issue is gone now for both Inkline 3 and 4. It was a problem with the files generated by the `unbuild` plugin.
