### ISSUE TITLE
[4.0.0-beta] Linking / Routing does not work

### ISSUE THREAD

**Issue by thunfisch987** [inkline/inkline#336]
* **What is the expected and current behavior?**
  Current Behavior:
  Linking and Routing when using to or :to does not work, but using href still works.
  When Clicking on the component, one is not send to the other page.
  The Link preview on hover in the browser does not work.
  There is no error thrown.

* **Steps to reproduce**
  Use a component like IButton, INavItem, INavBrand, etc. and use `to=""` or `:to="{}"` to link to another page.

* **Please tell us about your environment:**
    - Version: >=4.0.0-beta.9
    - Browser: all
    - Language: TypeScript

* **Other information**
  There is no error message ._.

**Comment by alexgrozav** [comment]
Hey! Ran into this as well and fixed it in the latest version. The `NuxtLink` component is no longer registered globally so I had to pass it in at plugin runtime. Can you confirm that it's fixed?

**Comment by thunfisch987** [comment]
the dependency config of @inkline/plugin is wrong 🤔 
installing it gives an error about the peer dependency @inkline/inkline@">=4"

**Comment by thunfisch987** [comment]
`code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @inkline/inkline@4.0.0-beta.15
npm ERR! node_modules/@inkline/inkline
npm ERR!   @inkline/inkline@"4.0.0-beta.15" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @inkline/inkline@">=4" from @inkline/plugin@1.2.4
npm ERR! node_modules/@inkline/plugin
npm ERR!   @inkline/plugin@"*" from the root project`

**Comment by thunfisch987** [comment]
The Links work now!
(installed @inkline/plugin 1.2.3 to avoid the error above)

**Comment by alexgrozav** [comment]
For now `@inkline/inkline` is a peer dependency of `@inkline/plugin` so that you can use whatever Inkline version you want without locking in to latest.

**Comment by thunfisch987** [comment]
Just noticed, the Linking only works when using `to` and not when using `:to`

When using `:to`
`[vite] Internal server error: Whitespace was expected.`

**Comment by alexgrozav** [comment]
Can you give me a code example to reproduce the error?

**Comment by thunfisch987** [comment]
```vue
<NuxtLink :to="{ name: 'about' }">Link1</NuxtLink> <!-- works -->
<IButton :to="{ name: 'about' }">Link2</IButton> <!-- does not work-->
```

**Comment by thunfisch987** [comment]
> Running `npm install -S @inkline/inkline@next` should fix the issue.

I tried that already and still got the same error

**Comment by thunfisch987** [comment]
Nevermind, sorry.....
I tried it again and it magically worked, there was probably something wrong with formatting or something

**Comment by alexgrozav** [comment]
No worries. Happy to hear it works as expected. 😊
