### ISSUE TITLE
icons do not render in i-select and i-modal

### ISSUE THREAD

**Issue by benderl** [inkline/inkline#339]
* **What is the expected and current behavior?**
When using i-select or i-modal components, output should be rendered as in documentation.
https://www.inkline.io/docs/forms/select
https://www.inkline.io/docs/components/modal
I expect dark icons in light color mode and vice versa.

* **Steps to reproduce**
Just create a new vue project with vite and add inkline components as documented.
I set up a simple code repo for demonstration: https://github.com/benderl/inkline-test

* **Please tell us about your environment:**
    - Version: latest (3.2.0), Vue 3.2.45
    - Browser: Chrome 109.0.5414.74
    - Language: ES

**Comment by benderl** [comment]
![Bildschirmfoto vom 2023-01-17 16-22-42](https://user-images.githubusercontent.com/7837691/213152936-b64d3d13-f956-4b81-9bd3-a6a5decd087b.png)
![Bildschirmfoto vom 2023-01-18 11-57-40](https://user-images.githubusercontent.com/7837691/213154236-28ae0e82-0d81-4571-a6f3-29163cb7b0b4.png)

Maybe this is related to #297 ? The I-Icon component does not appear in dom.

Select element:
![Bildschirmfoto vom 2023-01-18 11-56-32](https://user-images.githubusercontent.com/7837691/213154067-d2ba8af2-3fcb-4f5a-87e0-52cb276c471d.png)

Modal:
![Bildschirmfoto vom 2023-01-18 11-58-52](https://user-images.githubusercontent.com/7837691/213154464-4d5be7d4-4a63-4da5-84fc-4da2a277faf5.png)

**Comment by benderl** [comment]
I have set up the demo repo on CodeSandbox: https://codesandbox.io/p/sandbox/icy-hooks-u2je8n

**Comment by alexgrozav** [comment]
Hey! Most likely caused by the CSS `mask` cross-browser properties missing. Can you try the guide here https://www.inkline.io/docs/introduction/guides/postcss ?

**Comment by benderl** [comment]
Wow! Never thought of postcss with this issue. Thanks a lot, now everything is rendered as expected.
I updated the CodeSandbox with the changes.

**Comment by alexgrozav** [comment]
Happy to help! 🙏 When Inkline 4 will be released, this won't be needed anymore.
