### ISSUE TITLE
Uncaught TypeError: acc[part] is undefined

### ISSUE THREAD

**Issue by zozulinskyi** [inkline/inkline#341]
* **What is the expected and current behavior?**
I can't validate my form because errors didn't shown.
In console I see next: Uncaught TypeError: acc[part] is undefined

Problem in next code:
```
export function setValuesAlongPath(object, path, values) {
  if (path) {
    path.split(".").reduce((acc, part) => {
      Object.keys(values).forEach((key) => {
        acc[part][key] = values[key]; // -- here
      });
      return acc && acc[part];
    }, object);
  }
  Object.keys(values).forEach((key) => {
    object[key] = values[key];
  });
  return object;
}
```

* **Steps to reproduce**
https://stackblitz.com/edit/nuxt-starter-54aqla?file=app.vue

* **Please tell us about your environment:**
    - "@inkline/inkline": "^3.2.0",
    - "@inkline/nuxt": "^3.1.4",
    - "nuxt": "^3.1.1",

**Comment by pkej** [comment]
Hi,
I've tried to download the project from stackblitz but get some errors I can't identify, could you create a github repository I could clone that contains and show the error?

**Comment by alexgrozav** [comment]
The issue has been fixed in Inkline 4: https://stackblitz.com/edit/nuxt-starter-ux58ab?file=app.vue.
