### ISSUE TITLE
Layout width not changing

### ISSUE THREAD

**Issue by R0N1n-dev** [inkline/inkline#342]
* **Trying to change width of layout-aside component as shown in Design system docs**
  Width should change but is not. Stuck at 320px

* **Steps to reproduce**
Scaffold nuxt 3 project using npx nuxi init
Added inkline according to docs 
Added width to scss 
  
* **Please tell us about your environment:**
    - Version: >=3.2.0
    - Browser: [all | Chrome XX | Firefox XX  ]
    - Language: Javascript

* **Other information**
 Pics of code
![Screenshot_2023-02-01_09-05-40](https://user-images.githubusercontent.com/83344872/215965516-bd2e04e4-684b-4f2b-91aa-7a92491ba643.png)
![Screenshot_2023-02-01_09-06-32](https://user-images.githubusercontent.com/83344872/215965525-de94e02d-adbd-4cdb-953c-1f8d6a4cd7c6.png)

**Comment by zozulinskyi** [comment]
@R0N1n-dev hi. can you upload this sample to Stackblitz? Because, I don't have any problem with that.

**Comment by R0N1n-dev** [comment]
stackblitz.com/R0N1n-dev/nuxt3-inkline

**Comment by R0N1n-dev** [comment]
https://stackblitz.com/R0N1n-dev/nuxt3-inkline

**Comment by zozulinskyi** [comment]
@R0N1n-dev Not Found
Sorry, we couldn’t find the page you’re looking for.

**Comment by R0N1n-dev** [comment]
https://stackblitz.com/github/R0N1n-dev/nuxt3-inkline

Missed the github

**Comment by alexgrozav** [comment]
I know the DX is not ideal for changing CSS variables in Inkline 3, but this will all be updated when inkline@4 is released.

I've made a small fix to your example to have it working: https://stackblitz.com/edit/github-wq5oxe-aw9frs?file=layouts/default.vue

**Comment by R0N1n-dev** [comment]
Ok Thanks. Looking forward to v4
