### ISSUE TITLE
Breadcrumb Linking and Routing don't work with Nuxt 3

### ISSUE THREAD

**Issue by zozulinskyi** [inkline/inkline#343]
* **What is the expected and current behavior?**
I'm just use example from official website and can't receive expected result.

* **Steps to reproduce**
https://stackblitz.com/edit/nuxt-starter-gjdfm5?file=app.vue

* **Please tell us about your environment:**
    - "nuxt": "^3.1.2"
    - "@inkline/inkline": "^3.2.0"
    - "@inkline/nuxt": "^3.1.4"

**Comment by alexgrozav** [comment]
Released `inkline@3.2.1` that fixes the issue. Thank you for reporting it!

**Comment by zozulinskyi** [comment]
I have some problems with that. In the new version attribute "a" is worked correctly, but "to" is still broken. It's not mapped for nuxt-router/vue-router.

Also, now all IBreadcrumbItem is shown as a link, which is incorrect because the last (active) item can't have a link. 

https://stackblitz.com/edit/nuxt-starter-gjdfm5?file=pages/index.vue

**Comment by alexgrozav** [comment]
@zozulinskyi I believe that Nuxt 3 is no longer making their NuxtLink global.

**Comment by zozulinskyi** [comment]
@alexgrozav thank you. I guess something strange with mapping dynamic component to "a" tag.

Computed property "isTag" can be "router-link" or "a". But, in the documentation of [Vue](https://vuejs.org/api/built-in-special-attributes.html#is), I see the next one: "You can prefix the value of the is attribute with Vue: so that Vue will render the element as a Vue component instead"

And in my dev-tools I see something like that: `<a href="" to="" is="router-link">Link</a>` ([this code](https://github.com/inkline/inkline/blob/inkline%403/src/components/IBreadcrumb/components/IBreadcrumbItem/template.html#L7))

Also [here](https://github.com/inkline/inkline/blob/inkline%403/src/mixins/LinkableMixin.ts#L12) I always have an empty object when I try to print to the console of `this.$attrs`

I hope you understand me )

**Comment by alexgrozav** [comment]
@all-contributors add @zozulinskyi for bug reporting.
