### ISSUE TITLE
Navbar alignment does not work

### ISSUE THREAD

**Issue by BenoitPingris** [inkline/inkline#35]
* **I'm submitting a:**
  - [x] Bug Report
  
* **What is the current behavior?**
The navbar nav placement does not work

* **What is the expected behavior?**
The <i-nav/> should be positionned on the right of the navbar
It seems that some classes are missing
```html
<i-navbar-brand to="/">FLOWOLF</i-navbar-brand>
  <i-navbar-items class="_justify-content-end">
    <i-nav>
      <i-nav-item :to="{ name: 'index' }">Home</i-nav-item>
      <i-nav-item :to="{ name: 'about' }">About</i-nav-item>
      <i-nav-item :to="{ name: 'contact' }">Contact</i-nav-item>
    </i-nav>
</i-navbar-items>
```
The result is that the <i-nav/> is still on the left of the navbar.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [Chrome Version 73.0.3683.103 (Build officiel) (64 bits) ]
  - Language: [VueJS]

* **Other information**
I simply execute `npm install @inkline/inkline`

**Comment by alexgrozav** [comment]
Hey! Thank you for the bug report. It looks like the helper class is most likely missing.

If you inspect the `<i-navbar-items>` component, do you see the `_justify-content-end` class applied? 

<img width="325" alt="Screen Shot 2019-04-15 at 5 44 01 PM" src="https://user-images.githubusercontent.com/6179477/56141836-4185ac00-5fa6-11e9-9a4b-cdab48095299.png">

If not, make sure you include Inkline's CSS files to make the helper classes available.
~~~
import '@inkline/inkline/dist/inkline.css';
~~~

**Comment by BenoitPingris** [comment]
In fact, they are a lot of helper class that are missing :/ (like the text-center{left-right} and so on).
I did include the inkline.css file, I don't know why these classes aren't here :(

Furthermore, I'd like to report another bug I encountered. When I install another framework with npm (eg: `npm i vuelidate`, for some reasons, inkline is missing the postcss-preset-env and I have to reinstall it, that's weird ahah
Here's the log if you're interested:

```
 ERROR  Failed to compile with 3 errors8:25:22 AM

This dependency was not found:

* regenerator-runtime/runtime in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/login/Form.vue?vue&type=script&lang=js&, ./src/store/modules/user.js and 1 other

To install it, you can run: npm install --save regenerator-runtime/runtime
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-15T08_25_22_658Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
ERROR: Job failed: exit code 1
```

**Comment by alexgrozav** [comment]
Can you give me read access to the repo where this is happening? 

The postcss error only appears if you're trying to transpile inkline.

https://inkline.io/docs/introduction/customization

Anyway, best would be to actually have the code where this is happening to be able to give you a solution.

**Comment by alexgrozav** [comment]
I have found the issue. I'll provide an update in a few minutes.

**Comment by alexgrozav** [comment]
Can you confirm that it works after updating to 1.12.2?

**Comment by BenoitPingris** [comment]
I did update inkline to 1.12.2n and unfortunately as soon as I launch npm run serve I have the following error message:
```
 INFO  Starting development server...
 98% after emitting CopyPlugin                                                    

 ERROR  Failed to compile with 5 errors                                                                                                                                21:32:43

These dependencies were not found:

* @inkline/inkline in ./src/main.js
* @inkline/inkline/dist/inkline.css in ./src/main.js
* regenerator-runtime/runtime in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_mo
dules/vue-loader/lib??vue-loader-options!./src/components/login/Form.vue?vue&type=script&lang=js&, ./src/store/modules/user.js and 1 other

To install them, you can run: npm install --save @inkline/inkline @inkline/inkline/dist/inkline.css regenerator-runtime/runtime
```

**Comment by alexgrozav** [comment]
Ok I'm giving it another try with a fresh vue-cli project.

**Comment by alexgrozav** [comment]
I've added another update (1.12.3) which works with a fresh vue-cli project. It won't require you to install any postcss plugin now and also made sure the helper classes are included.

Thank you so much for reporting this. Having used the uncompiled version for testing until now, I didn't realize the compiled CSS file wasn't complete.

**Comment by BenoitPingris** [comment]
Oh nice, I switch to 1.12.3, rm node_modules and package-lock, did a `npm i && npm run serve` and it seems to work !
Nice thank you !

**Comment by alexgrozav** [comment]
Great! Let me know if there's any other issue. Also, thanks a lot for giving inkline a try and helping out!
