### ISSUE TITLE
Add `tag` to `props` which can be use to choose a HTML element to use for ICard

### ISSUE THREAD

**Issue by neilmerton** [inkline/inkline#356]
* **Summary**
Current `ICard` only generates a `div` tag as the main HTML element. It would be good to be able to specify a different HTML tag to use instead of `div`, for example `article`. This will help with generating improved semantic HTML.

* **Can you provide a basic example?**
The new `prop` can be `tag` with a `default` value of `div`.
When outputting the code in the `template` tag, using `component` with `:is="tag"` instead of `div`.

* **Motivation**
This will help to produce semantic HTML as the developer could specify `article`, `section` tags instead of `div`.

**Comment by alexgrozav** [comment]
Hey! I like the idea. Would you have the time to create a PR for this?

**Comment by alexgrozav** [comment]
Released with version `4.0.2`.
