### ISSUE TITLE
Styling aside part of layout still annoying like in v3

### ISSUE THREAD

**Issue by R0N1n-dev** [inkline/inkline#357]
Trying to change width of layout-aside component as shown in Design system docs
Width should change but is not. Stuck at 320px

Steps to reproduce
Scaffold nuxt 3 project using npx nuxi init
Added inkline according to docs on next.inkline
Added width to root

Please tell us about your environment:

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @inkline/plugin/nuxt@1.4.3
- Build Modules:    -

Had same issue with v3 Inkline and you said design token system will solve it but still shit annoying  trying to style aside component.

Please include how to change width of aside without just putting a design token without explaining what to do. coz its still a problem even with new version.
Its trial and error really. 
Cant use this till then. Suffering to change aside width. WTF again like v3???????????

**Comment by MasihTak** [comment]
I would like to ask you to refrain from using abusive or offensive language when communicating. This is not conducive to a healthy and respectful community. Please understand that developing and maintaining open-source software takes a lot of time and effort, and that we are doing our best to provide a useful and reliable product. If you have any specific questions or suggestions about the feature, please feel free to share them in a constructive and polite manner. We will try to address them as soon as possible. Thank you for your cooperation and understanding.

**Comment by alexgrozav** [comment]
Hi @R0N1n-dev! I understand you're frustrated, but I won't be able to help out unless you give me some reproduction code to work with.

- What does your template markup look like? 
- What does your css look like?

**Comment by R0N1n-dev** [comment]
It would be fitting to include on the layout page or design token page how to adjust the layout elements, so that its not about guessing what to do with the provided design token (--layout-aside--width).
You could also just send a snippet of how you would do it coz i dont know where to begin.


https://stackblitz.com/github/R0N1n-dev/Vue-Line
