### ISSUE TITLE
ISelect does not display default option

### ISSUE THREAD

**Issue by zozulinskyi** [inkline/inkline#378]
* **What is the expected and current behavior?**
If I set a default option for ISelect component this value does not display.

* **Steps to reproduce**
https://stackblitz.com/edit/inkline-wjkaby?file=src%2FApp.vue

**Comment by alexgrozav** [comment]
Thank you for reporting the issue.  I'm away on vacation right now, but will fix it sometime next week and leave a message here. 🙏

**Comment by alexgrozav** [comment]
Hey! The Inkline version in your reproduction points to Inkline 3. To have the first option selected in Inkline 3, you need the whole object as a value: https://stackblitz.com/edit/inkline-1yzsmb?file=src%2FApp.vue
