### ISSUE TITLE
ISelect search does not work

### ISSUE THREAD

**Issue by GiovaniAtBasf** [inkline/inkline#381]
* **What is the expected and current behavior?**
  If I enable autocomplete and search I expect the search event to be called, no such thing is happening.

* **Steps to reproduce**
  Create a select with autocomplete and listen to the search event, it never gets called. I have provided a stackblitz for you convenience.

* **Please tell us about your environment:**
    - Version: >=4.0.0
    - Browser: all
    - Language: all

* **Other information**
  [Stackblitz](https://stackblitz.com/edit/inkline-xkmuok?file=src%2FApp.vue)

**Comment by alexgrozav** [comment]
Hey @GiovaniAtBasf! The `ISelect` component does not support `autocomplete` anymore in Inkline 4. The code for Inkline 3's select component is still available [here](https://github.com/inkline/inkline/tree/inkline%403/src/components/ISelect), if you want to add it as a custom component to your project.

I'm actively working on creating a more complex and robust standalone Autocomplete component with support for multiple values, which will be released as part of the Inkline Pro components suite in Q4 2023.
