### ISSUE TITLE
Page flashes white background even when colorMode is dark

### ISSUE THREAD

**Issue by Curetix** [inkline/inkline#397]
I set the Inkline config in `nuxt.config.ts` like this:

```ts
inkline: {
  globals: {
    colorMode: "dark",
  },
},
```

But even with this the page background is white briefly when it is initially loaded, after which it transitions to the dark background. Other elements have the dark theme from the start.

https://github.com/inkline/inkline/assets/15160542/2ee89507-ef70-4a38-a003-cd4f82f11179

* Version: Inkline 4.6.1, Nuxt 3.8.0, Vue 3.3.7
* Browser: all
* Language: TypeScript

**Comment by alexgrozav** [comment]
Hey, this is an issue that appears with all Color Mode plugins when using SSR. There's no way of knowing the user's color mode preference so you have to start from either light or dark mode and switch to the other.

Setting `colorMode` to `dark` will add the `dark-theme` class as soon as Inkline is loaded, however to have an initial dark theme we'd need to set the `dark-theme` class even before that.

My suggestion would be to add `dark-theme` to your HTML attributes in Nuxt as follows:

```ts
defineNuxtConfig({
  inkline: {
    globals: {
      colorMode: 'dark',
    },
  },
  app: {
    head: {
      htmlAttrs: {
        class: 'dark-theme'
      }
    }
  }
})
```

This way, the flashing will disappear and `dark-theme` will be set as default right from the start. I've tested it locally, but please do confirm that it solves your issue 🙏

**Comment by Curetix** [comment]
> Hey, this is an issue that appears with all Color Mode plugins when using SSR. There's no way of knowing the user's color mode preference so you have to start from either light or dark mode and switch to the other.
> 
> Setting `colorMode` to `dark` will add the `dark-theme` class as soon as Inkline is loaded, however to have an initial dark theme we'd need to set the `dark-theme` class even before that.
> 
> My suggestion would be to add `dark-theme` to your HTML attributes in Nuxt as follows:
> 
> ```ts
> defineNuxtConfig({
>   inkline: {
>     globals: {
>       colorMode: 'dark',
>     },
>   },
>   app: {
>     head: {
>       htmlAttrs: {
>         class: 'dark-theme'
>       }
>     }
>   }
> })
> ```
> 
> This way, the flashing will disappear and `dark-theme` will be set as default right from the start. I've tested it locally, but please do confirm that it solves your issue 🙏

Thank you, that works indeed! My app is dark-theme only, so this is perfect.

**Comment by alexgrozav** [comment]
@Curetix happy to help! Enjoy!

@all-contributors add @Curetix for bug report.
