### ISSUE TITLE
Add Vue CLI Integration

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#42]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request

**Comment by mtancoigne** [comment]
What is missing for the Vue-cli integration ?

**Comment by alexgrozav** [comment]
We need to add generator code for easily installing inkline through the  cli. 

I found this article explaining how to do it: https://dev.to/vuevixens/how-to-build-a-vue-cli-plugin-3b6b

**Comment by mtancoigne** [comment]
I read the article, it explains the process really well. And as I understand, we need a separate repo for this plugin. Maybe it can be `vue-cli-plugin-inkline` ?

**Comment by alexgrozav** [comment]
Yes, `vue-cli-plugin-inkline` would be the proper name for it. I'm currently on vacation, but I'll create the repository for it.

**Comment by mtancoigne** [comment]
Ok, no problem :) I'll see if I can do something in the next few days.

**Comment by alexgrozav** [comment]
@mtancoigne What's the best way to keep in touch with you? Send me an email at alex@grozav.com
