### ISSUE TITLE
ISelect form focus issue

### ISSUE THREAD

**Issue by kuramen** [inkline/inkline#423]
**Describe the bug**
If an IForm has an ISelect input and if you press Enter on an other input, ISelect will open.

**To Reproduce**
1. Create and IForm with an IInput and an ISelect
3. Click on IInput and Press Enter

**Expected behavior**
Press enter doesn't open ISelect but submit IForm.

**Fix**
After a few searches, it's not a JS issue but an HTML one. We need to force <button> inside ISelect to have type="button". If not form will treat this button like submit one

**Comment by alexgrozav** [comment]
Fixed in #425. Thanks for reporting the issue.
