### ISSUE TITLE
[Documentation] - Helper classes

### ISSUE THREAD

**Issue by BenoitPingris** [inkline/inkline#46]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
We can see in some examples of the documentation that there are some helpers classes like the following `_text-center _text-white`.

I think it would be nice if there was a section in the documentation that would refer to these different classes so we don't have to inspect the code source or create our own classes.

I see that the [Typography](https://inkline.io/docs/core/typography) section already details some of these classes but they're not all there.

**Comment by alexgrozav** [comment]
Good point, I'll start working on this.

**Comment by alexgrozav** [comment]
Done in https://github.com/inkline/inkline.io/pull/32
