### ISSUE TITLE
"i-select" elements does not render default value

### ISSUE THREAD

**Issue by mtancoigne** [inkline/inkline#50]
* **I'm submitting a:**

  - [x] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
When creating `i-select` elements with a default value, the label is not rendered. I.e. : https://codepen.io/mtancoigne/pen/LoZVOq

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)
When creating a `i-select` element with a default value, the corresponding label should be displayed

* **Please tell us about your environment:**

  - Version: 1.14.0
  - Browser: Chrome XX, Firefox XX, not tested on the other
  - Language: ES6 and vanillaJS, not tested on other

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)
None

**Comment by alexgrozav** [comment]
Fixed in https://github.com/inkline/inkline/pull/56.
