### ISSUE TITLE
Disable scrolling of the page while a modal is shown

### ISSUE THREAD

**Issue by krajcovic46** [inkline/inkline#55]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request

  
* **What is the current behavior?**

Currently, swiping/scrolling while a modal is shown scrolls the faded page in the background.

* **What is the expected behavior?**

While a modal is shown, scrolling/swiping the page in the background should be disabled.

* **Please tell us about your environment:**

  - Version: 1.14.2
  - Browser: [Chrome | iOS 12.3 Safari]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

**Comment by alexgrozav** [comment]
Good point, I'll fix this in the next version. I'm currently on vacation until 23rd of May, so my work time is pretty limited. I'll still be able to answer messages, though. Thanks for reporting this.
