### ISSUE TITLE
Available Icons

### ISSUE THREAD

**Issue by adrazich** [inkline/inkline#58]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**

When I go to the [icon documentation](https://inkline.io/docs/components/icon) there are only a few icons shown for use. It doesn't contain a full list of available icons.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

A full list of all available icons or a link to which icons are available.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [**all** | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

I'm trying to figure out the best way to use icons for this framework. Are the icons on the documentation page the only icons available currently? Or do you have a link that shows a full list? I'm wondering if I should install Font Awesome for now instead?

**Comment by mtancoigne** [comment]
Hi @adrazich,

According to [the stylesheet](https://github.com/inkline/inkline/blob/master/src/css/config/_icons.styl), the icons in the documentation seems to be the only one available.

**Comment by adrazich** [comment]
Alright, that's what I was afraid of. Are more icons going to be added in the future? For now I will stick with font awesome.

**Comment by alexgrozav** [comment]
Hey @adrazich, 

The icons available are the ones natively used within Inkline's components (arrows, close icons, circles, etc.). I've tried to keep the list of icons as restricted as possible to not affect Inkline's size, while still providing a list of the most common icons.

You'll have to rely on a 3rd party icon framework such as Font Awesome for a complete spectrum of icons.
