### ISSUE TITLE
Switch from Stylus to SASS

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#60]
This would probably increase adoption. 

I wrote the project styles in Stylus simply because it's what I expected the SASS Indented syntax to be.

SASS ended up being the most used and appreciated option in State of CSS, while Stylus is the last. https://2019.stateofcss.com/technologies/pre-post-processors/

Everything written in Stylus would probably require minor changes to be turned into SASS (indented syntax).

Should we switch to SASS?

**Comment by mtancoigne** [comment]
As far as I can see, Stylus is not really used these days and the repo is not evolving really much.

Switching to SASS would bring a better integration with existing tools. I give a :+1: for the switch :)

Some links I have found around:

- https://www.slant.co/versus/762/764/~stylus_vs_sass
- https://stackshare.io/stackups/sass-vs-stylus, check the number of projects for both techs
- [Stylus repo](https://github.com/stylus/stylus/), check the last commits dates, the issues number and age, pending MRs
- [SASS repo](https://github.com/sass/sass), do the same as above

Even if I like diversity and choice, I think it's best when tools have a smooth interaction/integration.

**Comment by osazos** [comment]
Moving to SASS seems to be a better choice, you already argumented why.
In case SASS is choosen, should we use `.sass` or `.scss`syntax`? For me it should be `.scss`: [https://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass](https://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass)

**Comment by alexgrozav** [comment]
@osazos I suppose `.scss` is the most widely used, and is the one we should be using as well. Even though I prefer the indentation based syntax, it has some known problems (no support for multiline maps) when compared to the standard syntax.

**Comment by mtancoigne** [comment]
I started to convert some files here, and I think it won't be that hard to do the conversion. There are some Stylus methods that needs to be re-written in SCSS, but I haven't been blocked yet :)

**Comment by mtancoigne** [comment]
Here are the first changes, to continue the discussion: #64

Github don't show the diffs of renamed files, so it's a bit hard to compare without cloning first.

**Comment by alexgrozav** [comment]
@mtancoigne Great work so far! I'll be on vacation until 22nd of July, so I won't be able to help until then.

**Comment by TheJaredWilcurt** [comment]
I was pretty excited about Inkline, but when I went to customization and saw it wasn't using Sass it was an immediate "no" from me.

**Checkout Bootstrap's history:**

1. Creator of Bootstrap is asked by his friend, the creator of Less, to use Less when building Bootstrap.
1. Bootstrap 1 uses Less.
1. Community manually ports Bootstrap over to Sass
1. Boostrap 2 switches to support both Less and Sass (painful transition)
1. Bootstrap 3 and 4 are exclusively Sass

**Checkout Vuetify's history:**

1. Creator makes Vuetify as a side project, is curious about Stylus and wants to try it.
1. Tries out Stylus on the Vuetify project, with no expectation that it would become popular
1. Vuetify 1 becomes popular, community is upset by lack of Sass support.
1. Vuetify 2 drops Stylus and converts all code over to Sass

**Comment by TheJaredWilcurt** [comment]
Please see Satisfaction vs Usage chart from State of CSS 2019:

* https://2019.stateofcss.com/technologies/

`.sass` syntax is better for the common "everyday" stuff you do. `.scss` is good for beginners, or for niche cases, like tabular-data-like styles, or Sass maps. Here's a break down. The two files can interact with each other without any problem. So I tend to stick with `.sass` and only switch over to using `.scss` when I have a valid reason to. I've also written an extremely strict linting ruleset that you can use, or adopt things from:

* https://github.com/TheJaredWilcurt/tjw-sasslint-rules#proscons-of-sass-vs-scss-vs-css

**Comment by mtancoigne** [comment]
And the SASS compiler fails loudly when there is an issue in code (I think about undefined variables), where Stylus uses the variable string in output, silently breaking stuff.

**Comment by alexgrozav** [comment]
@TheJaredWilcurt I agree with what you wrote. Switching to SCSS will increase adoption, devs won't have to change tooling and it will also attract more contributors. Since we're using maps heavily throughout the project, we went for the `.scss` extension.

@mtancoigne has been actively working on the scss rewrite and I'll start the review, integration and documentation process once I'm back from vacation (in 2 days). 

We're getting close! 😃

**Comment by alexgrozav** [comment]
We're done with the Sass migration! Starting from [@inkline/inkline@1.16.1](https://github.com/inkline/inkline/releases/tag/1.16.1), stylesheets are entirely written in SCSS.

**Comment by TheJaredWilcurt** [comment]
@alexgrozav 

* https://github.com/inkline/inkline/blob/master/.github/contributing.md#stylus
