### ISSUE TITLE
Nuxt installation crashes

### ISSUE THREAD

**Issue by Merthod** [inkline/inkline#62]
* **I'm submitting a:**

  - [ X ] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
Nuxt compilation crashes at a brand new install.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.)

The following path, provided for Nuxtjs in the docs **does not exist**:
Link: https://inkline.io/docs/introduction/installation

Code:
```
module.exports = {
    modules: [ '@inkline/inkline/nuxt' ]
}
```

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [all]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

Changing /nuxt for nothing or /src also brings errors.

**Comment by alexgrozav** [comment]
Can you try version `1.15.3`? In `1.15.2` I forgot to include the `nuxt` folder in the published npm package. Sorry about that!

**Comment by alexgrozav** [comment]
There was a bit of trouble in `1.15.3` as well because of how webpack loads packages from node_modules in the Vue SSR plugin. The module itself worked, but wasn't loading properly. I got help from @pi0 (one of the nuxt.js devs) to fix it.
