### ISSUE TITLE
Add loading indicator

### ISSUE THREAD

**Issue by iwatakeshi** [inkline/inkline#63]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

Hi,

First of all, great job on this library. I just wanted to request a feature as described in the title. It would be nice to have a loading indicator similar to Semantic UI's [button](https://semantic-ui.com/elements/button.html#states). 

There are a few loading indicator libraries for Vue, however some are [outdated](https://github.com/Saeris/vue-spinners) or don't necessarily fit with Inkline's theme. I believe it would be best for this library to provide it's own loading indicator component, just like the progress bar that is provided out of the box.

Thanks!

**Comment by alexgrozav** [comment]
Hey! Thank you for the feedback. I'll add a loading spinner and loading button state for the next version.

**Comment by alexgrozav** [comment]
I've added an `ILoader` component in Inkline version 1.16.3. Check it out at https://inkline.io/docs/components/loader
