### ISSUE TITLE
Add a password input

### ISSUE THREAD

**Issue by jack-cooper** [inkline/inkline#72]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the expected behavior?**

Hi there, I'd like to start by saying wonderful job on this library and everything looks amazing. I've looked everywhere relevant I can find in both the docs and source and can't see an option to give an `i-input` `type="password"`, or a separate component to do essentially the same.

**Comment by alexgrozav** [comment]
Hey! Thank you so much for the kind words.

The `i-input` component uses a normal `input` behind the scenes and can be used together with type the usual way to create a password input: `<i-input type="password"></i-input>`.

I'll update the docs to reflect this information properly. Thank you!
