### ISSUE TITLE
Hovering Select menu does not change cursor style.

### ISSUE THREAD

**Issue by Cristy94** [inkline/inkline#74]
* **I'm submitting a:**

  - [X] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
**Select** component (dropdown) does not have `cursor: pointer` to indicate it is interactable. Not consistent with other UI elements.

* **What is the expected behavior?**
Hovering the dropdown should change the cursor to the hand icon.

* **Please tell us about your environment:**
https://inkline.io/docs/forms/select on Chrome 76, W10.

**Comment by alexgrozav** [comment]
Thank you for the suggestion. I've updated the `:focus` and `:hover` styling in #82.
