### ISSUE TITLE
No API for hamburger button or collapse in NavBar

### ISSUE THREAD

**Issue by tomtakumi** [inkline/inkline#78]
* **I'm submitting a:**

  - [ ] Bug Report
  - [X] Feature Request
  
* **What is the current behavior?**
I would like to be able to control collapsing the items when an item is clicked. Right now it remains collapsed even after you clicked 1 item. 
![image](https://user-images.githubusercontent.com/13040075/64434383-56c7b800-d0b8-11e9-9c10-ebe5e0057e8c.png)

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

**Comment by alexgrozav** [comment]
Thank you for reporting this! Fixed in #86. It will be released in `@inkline/inkline@1.15.7`.

**Comment by tomtakumi** [comment]
![image](https://user-images.githubusercontent.com/13040075/65415793-5d5f6a80-ddee-11e9-9e13-9def35c8ba8e.png)

@alexgrozav i hope I'm not bugging you about this but can't seem to make it work.

**Comment by alexgrozav** [comment]
Hey! Perhaps I misunderstood your request. 

You want to close the navbar when an `i-nav-item` is clicked. Am I correct?

**Comment by tomtakumi** [comment]
:) Yes you are correct. I don't know how stupid I am. I can't make it work. I've already updated to new version.
![image](https://user-images.githubusercontent.com/13040075/65764359-5c477980-e11d-11e9-9d81-35695313ddad.png)

**Comment by alexgrozav** [comment]
Hey! That was entirely my fault. I double checked the fix I made and it looks like using the `i-nav-item` as a `router-link` requires me to provide a native event.

I've fixed it in `@inkline/inkline@1.16.10` and it should be enabled out of the box. Can you try it out? 

Thank you for reporting this!

**Comment by tomtakumi** [comment]
Perfect! I can't believe you're running this wonderful UI alone.

**Comment by alexgrozav** [comment]
Thank you! I'm very proud of it. I hope it'll get more traction and I'll be able to have many regular contributors someday. However, I'll keep making it better until it does! :)
