### ISSUE TITLE
Have customizable styles

### ISSUE THREAD

**Issue by mtancoigne** [inkline/inkline#80]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**

Styles are mainly scoped in components, which makes them to customize.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

It would be great to be able to customize the framework.

* **Other information**

I'm used to import stylesheets and modify variables before the imports:

```scss
// well...
@import 'custom_vars';
// Inkline core, components, ...
@import '~inkline/xxx/variables';
@import '~inkline/xxx/base';
@import '~inkline/xxx/xxx';

// Custom overrides
@import 'overrides/xxx';
// ...
```
I expect the custom vars to be applied in Inkline components, which is not the case: styles inside components have their own imports, and customizations are not available (variants, colors, etc...)

A possible solution would be to extract the style from the components and provide some files that the dev can pick (i.e.: _everything_, _core only_, etc...)

**Comment by alexgrozav** [comment]
The `overrides/xxx` stylesheet will need to be included for every component, before the component styles (in order to override `!default`).

Try the methods described here: https://inkline.io/docs/introduction/customization

**Comment by mtancoigne** [comment]
Ok, I wasn't aware of this method for the styles, I think I'm getting old :)

Thanks, i'll try is as soon as possible.
