### ISSUE TITLE
Ability to only use some of the components

### ISSUE THREAD

**Issue by mtancoigne** [inkline/inkline#81]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**
Importing Inkline in a Vue project makes the the compiled "application.js" grow from 783kb to 3.05Mb (without using it).

* **What is the expected behavior?**
It would be great if we could only import the components we need.

**Comment by alexgrozav** [comment]
Have you tried the Basic Installation - Tree Shaking guide? https://inkline.io/docs/introduction/installation

It should work. If it doesn't, it's an issue.

**Comment by mtancoigne** [comment]
Well, I admit I didn't. This is great. Thanks again !

**Comment by mtancoigne** [comment]
This works but I still notice that with tree shaking and `INavbar` component, application.js is still 2.5Mo (during dev, so I guess the production build will be smaller)

**Comment by alexgrozav** [comment]
Hmm, that's weird. I'll investigate this.

**Comment by alexgrozav** [comment]
I've looked into it. With a freshly setup `@vue/cli` project, tree shaking is working as it should, and I'm not having the sizes you've mentioned.

No tree shaking 
![image](https://user-images.githubusercontent.com/6179477/64764768-7f81fe80-d54b-11e9-84ee-f4fed02b0935.png)


Tree shaking 
![image](https://user-images.githubusercontent.com/6179477/64764750-74c76980-d54b-11e9-905f-36aec6c1cd2a.png)
