### ISSUE TITLE
Treeshaking compile produce error

### ISSUE THREAD

**Issue by webidew** [inkline/inkline#91]
* **I'm submitting a:**

  - [*] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**

Treeshaking compiling produces error as below:

Module parse failed: Unexpected token (5:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export class PopupManager {
>     instances = {};
|     modalStack = [];
|     zIndex = 1000;

 @ ./node_modules/@inkline/inkline/src/helpers/index.js 21:0-57 21:0-57
 @ ./node_modules/@inkline/inkline/src/components/Select/script.js?vue&type=script&lang=js&
 @ ./node_modules/@inkline/inkline/src/components/Select/script.js?vue&type=script&lang=js&
 @ ./node_modules/@inkline/inkline/src/components/Select/index.vue
 @ ./node_modules/@inkline/inkline/src/components/index.js
 @ ./node_modules/@inkline/inkline/src/index.js

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 - package.json file
--------------------
{
  "name": "inkline.test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@inkline/inkline": "^1.16.12",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.0",
    "sass-resources-loader": "^2.0.1",
    "resolve-url-loader": "^3.1.0",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

main.js
---------
import Vue from 'vue'

import Inkline from '@/plugins/inkline.js'

import App from '@/layout/App.vue'
import router from '@/router'
import store from '@/store'

Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')

@/plugin/inkline.js
---------------------

import Vue from 'vue';
import '@inkline/inkline/src/index.scss';
import { Inkline, IButton, IForm, IInput } from '@inkline/inkline/src/index';

Vue.use(Inkline, {
    components: [
        IButton,
        IForm,
        IInput
    ]
});

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

**Comment by alexgrozav** [comment]
Thank you for the report. I'm looking into it.

**Comment by alexgrozav** [comment]
Hey, I've looked into it and the tree shaking is working fine. The part that you're missing is described in https://inkline.io/docs/introduction/installation at the Tree Shaking section. 

For vue-cli, you'll need to add Inkline to your transpiled dependencies in `vue.config.js` as follows:

~~~js
// vue.config.js

module.exports = {
    transpileDependencies: ["@inkline/inkline"]
}
~~~

**Comment by webidew** [comment]
Done that.... But still produces error... The error produced specifically says that unexpected token. I believe the problem was not on the code but there are one or some specific package required but you did not mentioned as node-sass and sass loader was already withun my dependencies package.

**Comment by webidew** [comment]
It was okay if I use normal usagr. It only produces error in treeshaking installation.

**Comment by alexgrozav** [comment]
I can go into a team viewer session and check it out with you. Can you message me on discord?

**Comment by webidew** [comment]
Outside right now. But I will try to ask my friends to zip the project and send it to my phone or upload it anywhere. Will send it to you.
