### ISSUE TITLE
Safari `middle-xs` in nested container is not working as expected

### ISSUE THREAD

**Issue by xvzf** [inkline/inkline#95]
* **I'm submitting a:**

  - [x] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
`middle-xs` attribute is ignored for nested containers in safari but working in other browsers.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)
You can have a look at my site here: <https://xvzf.tech> - code is in [this repo](https://github.com/xvzf/xvzf.tech)

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Browser: [ Safari 13  ]
  - Language: [ES6/7]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

**Comment by alexgrozav** [comment]
Hey! This seems to be related to how Safari treats `align-items: stretch`. Chrome and Firefox consider the stretched item to be 100% of the available height, but Safari doesn't.

The solution to your issue will be to add the `._height-100` helper class to the `<i-layout-content>` component as well:

~~~html
<i-layout-content class="_height-100">
...
</i-layout-content>
~~~

**Comment by alexgrozav** [comment]
However, I'll try to see if there's any workaround for making safari get the height properly.

**Comment by alexgrozav** [comment]
Another way you could proceed would to turn your `i-layout-content` into a flexbox element.

~~~html
<i-layout-content class="_display-flex _align-items-center">
...
</i-layout-content>
~~~

**Comment by xvzf** [comment]
Thanks @alexgrozav with the workaround everything is fine! :-)

**Comment by alexgrozav** [comment]
You're welcome! Thank you for using Inkline. :)
