### ISSUE TITLE
NuxtJs- get warning "export 'default' (imported as 'Inkline') was not found in '@inkline/inkline/src/index.js'

### ISSUE THREAD

**Issue by IsidroMar95** [inkline/inkline#97]
* **I'm submitting a:**

  - [x] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**
in a new Nuxt Project i want customize the colors and i follow the documentation, but when i run `npm run dev` the terminal throw me the next warning:
![Screenshot_1](https://user-images.githubusercontent.com/23019968/68089502-fd1d0900-fe2e-11e9-95f0-88b07b121114.png)
i dont know wheter my config is wrong or i'm skiping some step

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)
i've been following the documentation :
https://inkline.io/docs/introduction/customization
with an clean installation of nuxt (no other frameworks or plugins) and this is my configuration **nuxt.config.js:**
```
export default {
  mode: 'spa',
  /*
  ** Headers of the page
  */
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },
  /*
  ** Global CSS
  */
  css: [
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    '@nuxtjs/axios',
    '@inkline/inkline/nuxt',
    '@nuxtjs/style-resources'
  ],
  styleResources: {
    scss: '~/assets/variables.scss'
  },
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
  },
  /*
  ** Build configuration
  */
  inkline: {
    treeShaking: true,
    scss: true
  },
  build: {
    transpile: ['@inkline/inkline'],
    extend(config, ctx) {
    }
  }
}
```

**package.json:**

```
{
  "name": "front-kbis",
  "version": "1.0.0",
  "description": "FrontEnd del proyecto K-Bis elaborado con NuxtJs",
  "author": "Isidro Martinez",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@inkline/inkline": "^1.17.3",
    "@nuxtjs/axios": "^5.3.6",
    "nuxt": "^2.0.0"
  },
  "devDependencies": {
    "@nuxtjs/style-resources": "^1.0.0",
    "node-sass": "^4.13.0",
    "postcss-preset-env": "^6.7.0",
    "sass-loader": "^8.0.0"
  }
}

```

* **Please tell us about your environment:**

  - Version: 1.17.3
  - Browser: [all]
  - Language: [ ES6/7 | ES5]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)
The app still loading in the browser and doesn't work, if i'm doing something wrong please help me to configure this amazing design framwork:
![image](https://user-images.githubusercontent.com/23019968/68089821-681c0f00-fe32-11e9-94ea-ada557a59962.png)

**Comment by alexgrozav** [comment]
Fixed in version 1.17.4. Thank you for reporting the issue!
